scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
        - Webauthn\Bundle\Security\Authentication\Token\WebauthnToken

    totp:
        enabled: true
        issuer: '%env(WEBAUTHN_RELYING_PARTY_NAME)%'
        server_name: '%env(WEBAUTHN_RELYING_PARTY_ID)%'
        parameters:
            image: ''
        template: '@SchebTwoFactor/Authentication/form.html.twig'

    backup_codes:
        enabled: true
