<?php

declare(strict_types=1);

namespace App\Server\Players\Character;

/**
 * The professions and traits the game itself defines.
 *
 * Generated from the installation's own
 * `media/scripts/generated/characters/*.txt` — the same files the game
 * reads at start-up — so nothing here is guessed. Regenerate it when
 * the game's build changes.
 *
 * **`cost` means two different things**, which is the one trap here.
 * For a *trait* it is a rating: positive is an advantage you pay for
 * (athletic +10, strong +10), negative a drawback that refunds points
 * (weak -10, deaf -12). For a *profession* it is the price itself, so
 * the sign is inverted — veteran costs -8 as the dearest job, while
 * unemployed refunds +8. So `isTraitAdvantage` takes a trait's cost and
 * nothing else; a profession has no good-or-bad axis at all.
 *
 * `professionTrait` marks the sixteen traits a job grants rather than
 * anybody choosing them, and `uiName` is the game's own translation key.
 */
final class CharacterDefinitions
{
    /**
     * @var array<string, array{cost: int, uiName: string|null, icon: string|null, xpBoosts: array<string, int>, grantedTraits: list<string>}>
     */
    public const PROFESSIONS = [
        'burgerflipper' => [
            'cost' => 2,
            'uiName' => 'UI_prof_BurgerFlipper',
            'icon' => 'profession_burgerflipper',
            'xpBoosts' => ['Cooking' => 2, 'Maintenance' => 1, 'SmallBlade' => 1],
            'grantedTraits' => ['cook2'],
        ],
        'burglar' => [
            'cost' => -6,
            'uiName' => 'UI_prof_Burglar',
            'icon' => 'profession_burglar2',
            'xpBoosts' => ['Lightfoot' => 2, 'Nimble' => 2, 'Sneak' => 2],
            'grantedTraits' => ['burglar'],
        ],
        'carpenter' => [
            'cost' => -2,
            'uiName' => 'UI_prof_Carpenter',
            'icon' => 'profession_hammer2',
            'xpBoosts' => ['Carving' => 1, 'Maintenance' => 1, 'Masonry' => 1, 'SmallBlunt' => 1, 'Woodwork' => 4],
            'grantedTraits' => [],
        ],
        'chef' => [
            'cost' => -2,
            'uiName' => 'UI_prof_Chef',
            'icon' => 'profession_chef2',
            'xpBoosts' => ['Butchering' => 2, 'Cooking' => 4, 'Maintenance' => 1, 'SmallBlade' => 1],
            'grantedTraits' => ['cook2'],
        ],
        'constructionworker' => [
            'cost' => -2,
            'uiName' => 'UI_prof_constructionworker',
            'icon' => 'profession_constructionworker2',
            'xpBoosts' => ['Blunt' => 1, 'Maintenance' => 1, 'Masonry' => 2, 'SmallBlunt' => 2, 'Woodwork' => 1],
            'grantedTraits' => [],
        ],
        'doctor' => [
            'cost' => 0,
            'uiName' => 'UI_prof_Doctor',
            'icon' => 'profession_doctor2',
            'xpBoosts' => ['Doctor' => 6, 'SmallBlade' => 1],
            'grantedTraits' => [],
        ],
        'electrician' => [
            'cost' => -2,
            'uiName' => 'UI_prof_Electrician',
            'icon' => 'profession_electrician',
            'xpBoosts' => ['Electricity' => 5],
            'grantedTraits' => [],
        ],
        'engineer' => [
            'cost' => -4,
            'uiName' => 'UI_prof_Engineer',
            'icon' => 'profession_engineer',
            'xpBoosts' => ['Electricity' => 1, 'Masonry' => 1, 'Woodwork' => 1],
            'grantedTraits' => [],
        ],
        'farmer' => [
            'cost' => 0,
            'uiName' => 'UI_prof_Farmer',
            'icon' => 'profession_farmer2',
            'xpBoosts' => ['Farming' => 4, 'Husbandry' => 1, 'Strength' => 1],
            'grantedTraits' => [],
        ],
        'fireofficer' => [
            'cost' => 0,
            'uiName' => 'UI_prof_fireoff',
            'icon' => 'profession_fireofficer2',
            'xpBoosts' => ['Axe' => 1, 'Fitness' => 1, 'Sprinting' => 1, 'Strength' => 1],
            'grantedTraits' => [],
        ],
        'fisherman' => [
            'cost' => -2,
            'uiName' => 'UI_prof_Fisherman',
            'icon' => 'profession_fisher2',
            'xpBoosts' => ['Butchering' => 1, 'Fishing' => 3, 'PlantScavenging' => 1],
            'grantedTraits' => [],
        ],
        'fitnessinstructor' => [
            'cost' => -6,
            'uiName' => 'UI_prof_FitnessInstructor',
            'icon' => 'profession_fitnessinstructor',
            'xpBoosts' => ['Fitness' => 3, 'Sprinting' => 2, 'Strength' => 1],
            'grantedTraits' => ['nutritionist2'],
        ],
        'lumberjack' => [
            'cost' => 0,
            'uiName' => 'UI_prof_Lumberjack',
            'icon' => 'profession_lumberjack',
            'xpBoosts' => ['Axe' => 2, 'Maintenance' => 1, 'Strength' => 1],
            'grantedTraits' => ['axeman'],
        ],
        'mechanics' => [
            'cost' => -4,
            'uiName' => 'UI_prof_Mechanics',
            'icon' => 'profession_mechanic',
            'xpBoosts' => ['Mechanics' => 4, 'MetalWelding' => 1],
            'grantedTraits' => ['mechanics2'],
        ],
        'metalworker' => [
            'cost' => -4,
            'uiName' => 'UI_prof_MetalWorker',
            'icon' => 'profession_metalworker',
            'xpBoosts' => ['MetalWelding' => 4],
            'grantedTraits' => [],
        ],
        'nurse' => [
            'cost' => 0,
            'uiName' => 'UI_prof_Nurse',
            'icon' => 'profession_nurse',
            'xpBoosts' => ['Doctor' => 3, 'Fitness' => 1, 'Lightfoot' => 1],
            'grantedTraits' => ['nightowl'],
        ],
        'parkranger' => [
            'cost' => -4,
            'uiName' => 'UI_prof_parkranger',
            'icon' => 'profession_parkranger2',
            'xpBoosts' => ['Carving' => 1, 'Doctor' => 1, 'FlintKnapping' => 1, 'PlantScavenging' => 1, 'Trapping' => 1],
            'grantedTraits' => ['herbalist_prof'],
        ],
        'policeofficer' => [
            'cost' => -4,
            'uiName' => 'UI_prof_policeoff',
            'icon' => 'profession_policeofficer2',
            'xpBoosts' => ['Aiming' => 4, 'Nimble' => 1, 'Reloading' => 1],
            'grantedTraits' => [],
        ],
        'rancher' => [
            'cost' => 0,
            'uiName' => 'UI_prof_rancher',
            'icon' => 'profession_rancher',
            'xpBoosts' => ['Butchering' => 3, 'Fitness' => 1, 'Husbandry' => 4],
            'grantedTraits' => [],
        ],
        'repairman' => [
            'cost' => -2,
            'uiName' => 'UI_prof_Repairman',
            'icon' => 'profession_repairman2',
            'xpBoosts' => ['Maintenance' => 2, 'Masonry' => 1, 'SmallBlunt' => 1, 'Woodwork' => 1],
            'grantedTraits' => ['inventive_prof'],
        ],
        'securityguard' => [
            'cost' => -2,
            'uiName' => 'UI_prof_securityguard',
            'icon' => 'profession_securityguard2',
            'xpBoosts' => ['Lightfoot' => 1, 'SmallBlunt' => 1, 'Sprinting' => 2],
            'grantedTraits' => ['nightowl'],
        ],
        'smither' => [
            'cost' => -6,
            'uiName' => 'UI_prof_Smither',
            'icon' => 'profession_smither',
            'xpBoosts' => ['Blacksmith' => 4, 'Maintenance' => 1, 'SmallBlunt' => 1],
            'grantedTraits' => ['blacksmith2'],
        ],
        'tailor' => [
            'cost' => 2,
            'uiName' => 'UI_prof_Tailor',
            'icon' => 'profession_tailor',
            'xpBoosts' => ['Tailoring' => 4],
            'grantedTraits' => [],
        ],
        'unemployed' => [
            'cost' => 8,
            'uiName' => 'UI_prof_unemployed',
            'icon' => null,
            'xpBoosts' => [],
            'grantedTraits' => [],
        ],
        'veteran' => [
            'cost' => -8,
            'uiName' => 'UI_prof_Veteran',
            'icon' => 'profession_veteran2',
            'xpBoosts' => ['Aiming' => 2, 'Reloading' => 2],
            'grantedTraits' => ['desensitized'],
        ],
    ];

    /**
     * @var array<string, array{cost: int, uiName: string|null, icon: string|null, xpBoosts: array<string, int>, professionTrait: bool, exclusive: list<string>}>
     */
    public const TRAITS = [
        'adrenalinejunkie' => [
            'cost' => 4,
            'uiName' => 'UI_trait_AdrenalineJunkie',
            'icon' => 'trait_adrenalinejunkie',
            'xpBoosts' => [],
            'professionTrait' => false,
            'exclusive' => ['agoraphobic', 'claustrophobic', 'cowardly', 'desensitized'],
        ],
        'agoraphobic' => [
            'cost' => -4,
            'uiName' => 'UI_trait_agoraphobic',
            'icon' => 'trait_agoraphobic',
            'xpBoosts' => [],
            'professionTrait' => false,
            'exclusive' => ['adrenalinejunkie', 'brave', 'desensitized', 'claustrophobic'],
        ],
        'allthumbs' => [
            'cost' => -2,
            'uiName' => 'UI_trait_AllThumbs',
            'icon' => 'trait_allthumbs',
            'xpBoosts' => [],
            'professionTrait' => false,
            'exclusive' => ['dextrous'],
        ],
        'artisan' => [
            'cost' => 2,
            'uiName' => 'UI_trait_Artisan',
            'icon' => 'trait_artisan',
            'xpBoosts' => ['Glassmaking' => 1, 'Pottery' => 1],
            'professionTrait' => false,
            'exclusive' => [],
        ],
        'asthmatic' => [
            'cost' => -5,
            'uiName' => 'UI_trait_Asthmatic',
            'icon' => 'trait_asthmatic',
            'xpBoosts' => [],
            'professionTrait' => false,
            'exclusive' => [],
        ],
        'athletic' => [
            'cost' => 10,
            'uiName' => 'UI_trait_athletic',
            'icon' => 'trait_athletic',
            'xpBoosts' => ['Fitness' => 4],
            'professionTrait' => false,
            'exclusive' => ['overweight', 'fit', 'obese', 'out of shape', 'unfit', 'very underweight', 'smoker'],
        ],
        'axeman' => [
            'cost' => 0,
            'uiName' => 'UI_trait_axeman',
            'icon' => 'trait_axeman',
            'xpBoosts' => [],
            'professionTrait' => true,
            'exclusive' => [],
        ],
        'baseballplayer' => [
            'cost' => 4,
            'uiName' => 'UI_trait_PlaysBaseball',
            'icon' => 'trait_baseballplayer',
            'xpBoosts' => ['Blunt' => 1],
            'professionTrait' => false,
            'exclusive' => [],
        ],
        'blacksmith' => [
            'cost' => 6,
            'uiName' => 'UI_trait_Blacksmith',
            'icon' => 'trait_blacksmith',
            'xpBoosts' => ['Blacksmith' => 2, 'Maintenance' => 1],
            'professionTrait' => false,
            'exclusive' => ['blacksmith2'],
        ],
        'blacksmith2' => [
            'cost' => 0,
            'uiName' => 'UI_trait_Blacksmith',
            'icon' => 'trait_blacksmith2',
            'xpBoosts' => [],
            'professionTrait' => true,
            'exclusive' => ['blacksmith'],
        ],
        'brave' => [
            'cost' => 4,
            'uiName' => 'UI_trait_brave',
            'icon' => 'trait_brave',
            'xpBoosts' => [],
            'professionTrait' => false,
            'exclusive' => ['cowardly', 'agoraphobic', 'claustrophobic', 'desensitized'],
        ],
        'brawler' => [
            'cost' => 6,
            'uiName' => 'UI_trait_BarFighter',
            'icon' => 'trait_brawler',
            'xpBoosts' => ['Axe' => 1, 'Blunt' => 1],
            'professionTrait' => false,
            'exclusive' => [],
        ],
        'burglar' => [
            'cost' => 0,
            'uiName' => 'UI_prof_Burglar',
            'icon' => 'trait_burglar',
            'xpBoosts' => [],
            'professionTrait' => true,
            'exclusive' => [],
        ],
        'claustrophobic' => [
            'cost' => -4,
            'uiName' => 'UI_trait_claustro',
            'icon' => 'trait_claustrophobic',
            'xpBoosts' => [],
            'professionTrait' => false,
            'exclusive' => ['adrenalinejunkie', 'agoraphobic', 'brave', 'desensitized'],
        ],
        'clumsy' => [
            'cost' => -2,
            'uiName' => 'UI_trait_clumsy',
            'icon' => 'trait_clumsy',
            'xpBoosts' => [],
            'professionTrait' => false,
            'exclusive' => ['graceful'],
        ],
        'conspicuous' => [
            'cost' => -4,
            'uiName' => 'UI_trait_Conspicuous',
            'icon' => 'trait_conspicuous',
            'xpBoosts' => [],
            'professionTrait' => false,
            'exclusive' => ['inconspicuous'],
        ],
        'cook' => [
            'cost' => 3,
            'uiName' => 'UI_trait_Cook',
            'icon' => 'trait_cook',
            'xpBoosts' => ['Butchering' => 1, 'Cooking' => 2],
            'professionTrait' => false,
            'exclusive' => ['cook2'],
        ],
        'cook2' => [
            'cost' => 0,
            'uiName' => 'UI_trait_Cook',
            'icon' => 'trait_cook2',
            'xpBoosts' => [],
            'professionTrait' => true,
            'exclusive' => ['cook'],
        ],
        'cowardly' => [
            'cost' => -2,
            'uiName' => 'UI_trait_cowardly',
            'icon' => 'trait_cowardly',
            'xpBoosts' => [],
            'professionTrait' => false,
            'exclusive' => ['adrenalinejunkie', 'brave', 'desensitized'],
        ],
        'crafty' => [
            'cost' => 3,
            'uiName' => 'UI_trait_Crafty',
            'icon' => 'trait_crafty',
            'xpBoosts' => [],
            'professionTrait' => false,
            'exclusive' => ['fastlearner', 'slowlearner'],
        ],
        'deaf' => [
            'cost' => -12,
            'uiName' => 'UI_trait_deaf',
            'icon' => 'trait_deaf',
            'xpBoosts' => [],
            'professionTrait' => false,
            'exclusive' => ['hardofhearing', 'keenhearing'],
        ],
        'desensitized' => [
            'cost' => 0,
            'uiName' => 'UI_trait_Desensitized',
            'icon' => 'trait_desensitized',
            'xpBoosts' => [],
            'professionTrait' => true,
            'exclusive' => ['adrenalinejunkie', 'agoraphobic', 'brave', 'claustrophobic', 'cowardly', 'hemophobic'],
        ],
        'dextrous' => [
            'cost' => 2,
            'uiName' => 'UI_trait_Dexterous',
            'icon' => 'trait_dextrous',
            'xpBoosts' => [],
            'professionTrait' => false,
            'exclusive' => ['allthumbs'],
        ],
        'disorganized' => [
            'cost' => -6,
            'uiName' => 'UI_trait_Disorganized',
            'icon' => 'trait_disorganized',
            'xpBoosts' => [],
            'professionTrait' => false,
            'exclusive' => ['organized'],
        ],
        'eagleeyed' => [
            'cost' => 4,
            'uiName' => 'UI_trait_eagleeyed',
            'icon' => 'trait_eagleeyed',
            'xpBoosts' => [],
            'professionTrait' => false,
            'exclusive' => ['shortsighted'],
        ],
        'emaciated' => [
            'cost' => -10,
            'uiName' => 'UI_trait_emaciated',
            'icon' => 'trait_emaciated',
            'xpBoosts' => [],
            'professionTrait' => true,
            'exclusive' => ['obese', 'overweight'],
        ],
        'fasthealer' => [
            'cost' => 6,
            'uiName' => 'UI_trait_FastHealer',
            'icon' => 'trait_fasthealer',
            'xpBoosts' => [],
            'professionTrait' => false,
            'exclusive' => ['slowhealer'],
        ],
        'fastlearner' => [
            'cost' => 6,
            'uiName' => 'UI_trait_FastLearner',
            'icon' => 'trait_fastlearner',
            'xpBoosts' => [],
            'professionTrait' => false,
            'exclusive' => ['crafty', 'slowlearner'],
        ],
        'fastreader' => [
            'cost' => 2,
            'uiName' => 'UI_trait_FastReader',
            'icon' => 'trait_fastreader',
            'xpBoosts' => [],
            'professionTrait' => false,
            'exclusive' => ['slowreader', 'illiterate'],
        ],
        'feeble' => [
            'cost' => -6,
            'uiName' => 'UI_trait_feeble',
            'icon' => 'trait_feeble',
            'xpBoosts' => ['Strength' => -2],
            'professionTrait' => false,
            'exclusive' => ['stout', 'strong', 'weak'],
        ],
        'firstaid' => [
            'cost' => 2,
            'uiName' => 'UI_trait_FirstAid',
            'icon' => 'trait_firstaid',
            'xpBoosts' => ['Doctor' => 1],
            'professionTrait' => false,
            'exclusive' => [],
        ],
        'fishing' => [
            'cost' => 4,
            'uiName' => 'UI_trait_Fishing',
            'icon' => 'trait_fishing',
            'xpBoosts' => ['Fishing' => 1],
            'professionTrait' => false,
            'exclusive' => [],
        ],
        'fit' => [
            'cost' => 6,
            'uiName' => 'UI_trait_fit',
            'icon' => 'trait_fit',
            'xpBoosts' => ['Fitness' => 2],
            'professionTrait' => false,
            'exclusive' => ['athletic', 'obese', 'out of shape', 'overweight', 'unfit'],
        ],
        'formerscout' => [
            'cost' => 6,
            'uiName' => 'UI_trait_Scout',
            'icon' => 'trait_formerscout',
            'xpBoosts' => ['Doctor' => 1, 'Fishing' => 1, 'PlantScavenging' => 1],
            'professionTrait' => false,
            'exclusive' => [],
        ],
        'gardener' => [
            'cost' => 2,
            'uiName' => 'UI_trait_Gardener',
            'icon' => 'trait_gardener',
            'xpBoosts' => ['Farming' => 1],
            'professionTrait' => false,
            'exclusive' => [],
        ],
        'graceful' => [
            'cost' => 4,
            'uiName' => 'UI_trait_graceful',
            'icon' => 'trait_graceful',
            'xpBoosts' => [],
            'professionTrait' => false,
            'exclusive' => ['clumsy'],
        ],
        'gymnast' => [
            'cost' => 5,
            'uiName' => 'UI_trait_Gymnast',
            'icon' => 'trait_gymnast',
            'xpBoosts' => ['Lightfoot' => 1, 'Nimble' => 1],
            'professionTrait' => false,
            'exclusive' => [],
        ],
        'handy' => [
            'cost' => 8,
            'uiName' => 'UI_trait_handy',
            'icon' => 'trait_handy',
            'xpBoosts' => ['Carving' => 1, 'Maintenance' => 1, 'Masonry' => 1, 'Woodwork' => 1],
            'professionTrait' => false,
            'exclusive' => [],
        ],
        'hardofhearing' => [
            'cost' => -4,
            'uiName' => 'UI_trait_hardhear',
            'icon' => 'trait_hardofhearing',
            'xpBoosts' => [],
            'professionTrait' => false,
            'exclusive' => ['deaf', 'keenhearing'],
        ],
        'heartyappetite' => [
            'cost' => -4,
            'uiName' => 'UI_trait_heartyappetite',
            'icon' => 'trait_heartyappetite',
            'xpBoosts' => [],
            'professionTrait' => false,
            'exclusive' => ['lighteater', 'very underweight'],
        ],
        'hemophobic' => [
            'cost' => -5,
            'uiName' => 'UI_trait_Hemophobic',
            'icon' => 'trait_hemophobic',
            'xpBoosts' => [],
            'professionTrait' => false,
            'exclusive' => ['desensitized'],
        ],
        'herbalist' => [
            'cost' => 4,
            'uiName' => 'UI_trait_Herbalist',
            'icon' => 'trait_herbalist',
            'xpBoosts' => ['PlantScavenging' => 1],
            'professionTrait' => false,
            'exclusive' => ['herbalist_prof'],
        ],
        'herbalist_prof' => [
            'cost' => 0,
            'uiName' => 'UI_trait_Herbalist',
            'icon' => 'trait_herbalist_prof',
            'xpBoosts' => ['PlantScavenging' => 1],
            'professionTrait' => true,
            'exclusive' => ['herbalist'],
        ],
        'highthirst' => [
            'cost' => -2,
            'uiName' => 'UI_trait_HighThirst',
            'icon' => 'trait_highthirst',
            'xpBoosts' => [],
            'professionTrait' => false,
            'exclusive' => ['lowthirst'],
        ],
        'hiker' => [
            'cost' => 5,
            'uiName' => 'UI_trait_Hiker',
            'icon' => 'trait_hiker',
            'xpBoosts' => ['PlantScavenging' => 1, 'Trapping' => 1],
            'professionTrait' => false,
            'exclusive' => [],
        ],
        'hunter' => [
            'cost' => 8,
            'uiName' => 'UI_trait_Hunter',
            'icon' => 'trait_hunter',
            'xpBoosts' => ['Aiming' => 1, 'Butchering' => 1, 'SmallBlade' => 1, 'Sneak' => 1, 'Tracking' => 1],
            'professionTrait' => false,
            'exclusive' => [],
        ],
        'illiterate' => [
            'cost' => -10,
            'uiName' => 'UI_trait_Illiterate',
            'icon' => 'trait_illiterate',
            'xpBoosts' => [],
            'professionTrait' => false,
            'exclusive' => ['fastreader', 'slowreader'],
        ],
        'inconspicuous' => [
            'cost' => 4,
            'uiName' => 'UI_trait_Inconspicuous',
            'icon' => 'trait_inconspicuous',
            'xpBoosts' => [],
            'professionTrait' => false,
            'exclusive' => ['conspicuous'],
        ],
        'insomniac' => [
            'cost' => -6,
            'uiName' => 'UI_trait_Insomniac',
            'icon' => 'trait_insomniac',
            'xpBoosts' => [],
            'professionTrait' => false,
            'exclusive' => [],
        ],
        'inventive' => [
            'cost' => 2,
            'uiName' => 'UI_trait_Inventive',
            'icon' => 'trait_inventive',
            'xpBoosts' => [],
            'professionTrait' => false,
            'exclusive' => ['inventive_prof'],
        ],
        'inventive_prof' => [
            'cost' => 0,
            'uiName' => 'UI_trait_Inventive',
            'icon' => 'trait_inventive_prof',
            'xpBoosts' => [],
            'professionTrait' => true,
            'exclusive' => ['inventive'],
        ],
        'irongut' => [
            'cost' => 2,
            'uiName' => 'UI_trait_IronGut',
            'icon' => 'trait_irongut',
            'xpBoosts' => [],
            'professionTrait' => false,
            'exclusive' => ['weakstomach'],
        ],
        'jogger' => [
            'cost' => 4,
            'uiName' => 'UI_trait_Jogger',
            'icon' => 'trait_jogger',
            'xpBoosts' => ['Sprinting' => 1],
            'professionTrait' => false,
            'exclusive' => [],
        ],
        'keenhearing' => [
            'cost' => 6,
            'uiName' => 'UI_trait_keenhearing',
            'icon' => 'trait_keenhearing',
            'xpBoosts' => [],
            'professionTrait' => false,
            'exclusive' => ['deaf', 'hardofhearing'],
        ],
        'lighteater' => [
            'cost' => 2,
            'uiName' => 'UI_trait_lighteater',
            'icon' => 'trait_lighteater',
            'xpBoosts' => [],
            'professionTrait' => false,
            'exclusive' => ['heartyappetite', 'obese'],
        ],
        'lowthirst' => [
            'cost' => 2,
            'uiName' => 'UI_trait_LowThirst',
            'icon' => 'trait_lowthirst',
            'xpBoosts' => [],
            'professionTrait' => false,
            'exclusive' => ['highthirst'],
        ],
        'marksman' => [
            'cost' => 0,
            'uiName' => 'UI_trait_marksman',
            'icon' => 'trait_marksman',
            'xpBoosts' => [],
            'professionTrait' => true,
            'exclusive' => [],
        ],
        'mason' => [
            'cost' => 2,
            'uiName' => 'UI_trait_Mason',
            'icon' => 'trait_mason',
            'xpBoosts' => ['Masonry' => 2],
            'professionTrait' => false,
            'exclusive' => [],
        ],
        'mechanics' => [
            'cost' => 3,
            'uiName' => 'UI_trait_Mechanics',
            'icon' => 'trait_mechanics',
            'xpBoosts' => ['Mechanics' => 1],
            'professionTrait' => false,
            'exclusive' => ['mechanics2'],
        ],
        'mechanics2' => [
            'cost' => 0,
            'uiName' => 'UI_trait_Mechanics',
            'icon' => 'trait_mechanics2',
            'xpBoosts' => [],
            'professionTrait' => true,
            'exclusive' => ['mechanics'],
        ],
        'needslesssleep' => [
            'cost' => 3,
            'uiName' => 'UI_trait_LessSleep',
            'icon' => 'trait_needslesssleep',
            'xpBoosts' => [],
            'professionTrait' => false,
            'exclusive' => ['needsmoresleep'],
        ],
        'needsmoresleep' => [
            'cost' => -4,
            'uiName' => 'UI_trait_MoreSleep',
            'icon' => 'trait_needsmoresleep',
            'xpBoosts' => [],
            'professionTrait' => false,
            'exclusive' => ['needslesssleep'],
        ],
        'nightowl' => [
            'cost' => 0,
            'uiName' => 'UI_trait_nightowl',
            'icon' => 'trait_nightowl',
            'xpBoosts' => [],
            'professionTrait' => true,
            'exclusive' => [],
        ],
        'nightvision' => [
            'cost' => 3,
            'uiName' => 'UI_trait_NightVision',
            'icon' => 'trait_nightvision',
            'xpBoosts' => [],
            'professionTrait' => false,
            'exclusive' => [],
        ],
        'nutritionist' => [
            'cost' => 2,
            'uiName' => 'UI_trait_nutritionist',
            'icon' => 'trait_nutritionist',
            'xpBoosts' => [],
            'professionTrait' => false,
            'exclusive' => ['nutritionist2'],
        ],
        'nutritionist2' => [
            'cost' => 0,
            'uiName' => 'UI_trait_nutritionist',
            'icon' => 'trait_nutritionist2',
            'xpBoosts' => [],
            'professionTrait' => true,
            'exclusive' => ['nutritionist'],
        ],
        'obese' => [
            'cost' => 0,
            'uiName' => 'UI_trait_obese',
            'icon' => 'trait_obese',
            'xpBoosts' => ['Fitness' => -2],
            'professionTrait' => true,
            'exclusive' => ['athletic', 'emaciated', 'fit', 'lighteater', 'very underweight', 'underweight', 'overweight'],
        ],
        'organized' => [
            'cost' => 4,
            'uiName' => 'UI_trait_Packmule',
            'icon' => 'trait_organized',
            'xpBoosts' => [],
            'professionTrait' => false,
            'exclusive' => ['disorganized'],
        ],
        'out of shape' => [
            'cost' => -6,
            'uiName' => 'UI_trait_outofshape',
            'icon' => null,
            'xpBoosts' => ['Fitness' => -2],
            'professionTrait' => false,
            'exclusive' => ['athletic', 'fit', 'unfit'],
        ],
        'outdoorsman' => [
            'cost' => 2,
            'uiName' => 'UI_trait_outdoorsman',
            'icon' => 'trait_outdoorsman',
            'xpBoosts' => [],
            'professionTrait' => false,
            'exclusive' => [],
        ],
        'overweight' => [
            'cost' => 0,
            'uiName' => 'UI_trait_overweight',
            'icon' => 'trait_overweight',
            'xpBoosts' => ['Fitness' => -1],
            'professionTrait' => true,
            'exclusive' => ['athletic', 'fit', 'emaciated', 'very underweight', 'underweight'],
        ],
        'pacifist' => [
            'cost' => -5,
            'uiName' => 'UI_trait_Pacifist',
            'icon' => 'trait_pacifist',
            'xpBoosts' => [],
            'professionTrait' => false,
            'exclusive' => [],
        ],
        'pronetoillness' => [
            'cost' => -4,
            'uiName' => 'UI_trait_pronetoillness',
            'icon' => 'trait_pronetoillness',
            'xpBoosts' => [],
            'professionTrait' => false,
            'exclusive' => ['resilient'],
        ],
        'resilient' => [
            'cost' => 4,
            'uiName' => 'UI_trait_resilient',
            'icon' => 'trait_resilient',
            'xpBoosts' => [],
            'professionTrait' => false,
            'exclusive' => ['pronetoillness'],
        ],
        'shortsighted' => [
            'cost' => -2,
            'uiName' => 'UI_trait_shortsigh',
            'icon' => 'trait_shortsighted',
            'xpBoosts' => [],
            'professionTrait' => false,
            'exclusive' => ['eagleeyed'],
        ],
        'slowhealer' => [
            'cost' => -3,
            'uiName' => 'UI_trait_SlowHealer',
            'icon' => 'trait_slowhealer',
            'xpBoosts' => [],
            'professionTrait' => false,
            'exclusive' => ['fasthealer'],
        ],
        'slowlearner' => [
            'cost' => -6,
            'uiName' => 'UI_trait_SlowLearner',
            'icon' => 'trait_slowlearner',
            'xpBoosts' => [],
            'professionTrait' => false,
            'exclusive' => ['crafty', 'fastlearner'],
        ],
        'slowreader' => [
            'cost' => -2,
            'uiName' => 'UI_trait_SlowReader',
            'icon' => 'trait_slowreader',
            'xpBoosts' => [],
            'professionTrait' => false,
            'exclusive' => ['fastreader', 'illiterate'],
        ],
        'smoker' => [
            'cost' => -3,
            'uiName' => 'UI_trait_Smoker',
            'icon' => 'trait_smoker',
            'xpBoosts' => [],
            'professionTrait' => false,
            'exclusive' => ['athletic'],
        ],
        'speeddemon' => [
            'cost' => 1,
            'uiName' => 'UI_trait_SpeedDemon',
            'icon' => 'trait_speeddemon',
            'xpBoosts' => [],
            'professionTrait' => false,
            'exclusive' => ['sundaydriver'],
        ],
        'stout' => [
            'cost' => 6,
            'uiName' => 'UI_trait_stout',
            'icon' => 'trait_stout',
            'xpBoosts' => ['Strength' => 2],
            'professionTrait' => false,
            'exclusive' => ['feeble', 'strong', 'weak'],
        ],
        'strong' => [
            'cost' => 10,
            'uiName' => 'UI_trait_strong',
            'icon' => 'trait_strong',
            'xpBoosts' => ['Strength' => 4],
            'professionTrait' => false,
            'exclusive' => ['feeble', 'stout', 'weak'],
        ],
        'sundaydriver' => [
            'cost' => -1,
            'uiName' => 'UI_trait_SundayDriver',
            'icon' => 'trait_sundaydriver',
            'xpBoosts' => [],
            'professionTrait' => false,
            'exclusive' => ['speeddemon'],
        ],
        'tailor' => [
            'cost' => 4,
            'uiName' => 'UI_trait_Tailor',
            'icon' => 'trait_tailor',
            'xpBoosts' => ['Tailoring' => 1],
            'professionTrait' => false,
            'exclusive' => [],
        ],
        'target_shooter' => [
            'cost' => 5,
            'uiName' => 'UI_trait_target_shooter',
            'icon' => 'trait_target_shooter',
            'xpBoosts' => ['Aiming' => 1],
            'professionTrait' => false,
            'exclusive' => [],
        ],
        'thickskinned' => [
            'cost' => 8,
            'uiName' => 'UI_trait_thickskinned',
            'icon' => 'trait_thickskinned',
            'xpBoosts' => [],
            'professionTrait' => false,
            'exclusive' => ['thinskinned'],
        ],
        'thinskinned' => [
            'cost' => -8,
            'uiName' => 'UI_trait_ThinSkinned',
            'icon' => 'trait_thinskinned',
            'xpBoosts' => [],
            'professionTrait' => false,
            'exclusive' => ['thickskinned'],
        ],
        'tinkerer' => [
            'cost' => 4,
            'uiName' => 'UI_trait_tinkerer',
            'icon' => 'trait_tinkerer',
            'xpBoosts' => ['Maintenance' => 1],
            'professionTrait' => false,
            'exclusive' => [],
        ],
        'underweight' => [
            'cost' => 0,
            'uiName' => 'UI_trait_underweight',
            'icon' => 'trait_underweight',
            'xpBoosts' => ['Fitness' => -1],
            'professionTrait' => true,
            'exclusive' => ['obese', 'very underweight', 'overweight'],
        ],
        'unfit' => [
            'cost' => -10,
            'uiName' => 'UI_trait_unfit',
            'icon' => 'trait_unfit',
            'xpBoosts' => ['Fitness' => -4],
            'professionTrait' => false,
            'exclusive' => ['athletic', 'fit', 'out of shape'],
        ],
        'very underweight' => [
            'cost' => 0,
            'uiName' => 'UI_trait_veryunderweight',
            'icon' => null,
            'xpBoosts' => ['Fitness' => -2],
            'professionTrait' => true,
            'exclusive' => ['athletic', 'obese', 'overweight', 'heartyappetite', 'underweight'],
        ],
        'weak' => [
            'cost' => -10,
            'uiName' => 'UI_trait_weak',
            'icon' => 'trait_weak',
            'xpBoosts' => ['Strength' => -5],
            'professionTrait' => false,
            'exclusive' => ['feeble', 'stout', 'strong'],
        ],
        'weakstomach' => [
            'cost' => -2,
            'uiName' => 'UI_trait_WeakStomach',
            'icon' => 'trait_weakstomach',
            'xpBoosts' => [],
            'professionTrait' => false,
            'exclusive' => ['irongut'],
        ],
        'weightgain' => [
            'cost' => -2,
            'uiName' => 'UI_trait_weightgain',
            'icon' => 'trait_weightgain',
            'xpBoosts' => [],
            'professionTrait' => false,
            'exclusive' => ['weightloss'],
        ],
        'weightloss' => [
            'cost' => -2,
            'uiName' => 'UI_trait_weightloss',
            'icon' => 'trait_weightloss',
            'xpBoosts' => [],
            'professionTrait' => false,
            'exclusive' => ['weightgain'],
        ],
        'whittler' => [
            'cost' => 2,
            'uiName' => 'UI_trait_Whittler',
            'icon' => 'trait_whittler',
            'xpBoosts' => ['Carving' => 2],
            'professionTrait' => false,
            'exclusive' => [],
        ],
        'wildernessknowledge' => [
            'cost' => 8,
            'uiName' => 'UI_trait_WildernessKnowledge',
            'icon' => 'trait_wildernessknowledge',
            'xpBoosts' => ['Carving' => 1, 'FlintKnapping' => 1, 'Maintenance' => 1, 'PlantScavenging' => 1],
            'professionTrait' => false,
            'exclusive' => [],
        ],
    ];

    /**
     * A trait helps rather than hurts.
     *
     * Traits only: a profession's cost is a price, not a rating, and
     * its sign runs the other way.
     */
    public static function isTraitAdvantage(int $cost): bool
    {
        return $cost > 0;
    }
}
