<?php

declare(strict_types=1);

namespace App\Server\Config;

/**
 * The server.ini options this game build defines. Generated — do not edit.
 *
 * Same provenance as `SandboxSchema`, with two differences that come
 * from the game rather than from us:
 *
 *   - `ServerOption` has no translated names, only tooltips, under the
 *     key `UI_ServerOption_<Name>_tooltip`. So the technical name is
 *     what the operator sees, with the tooltip explaining it.
 *   - the grouping is `SettingsTable[1]`, the same table the game's own
 *     server settings screen uses. It is taken from the game rather
 *     than invented here, which is what keeps settings that belong
 *     together in one place.
 *
 * The INI file on the server is still the truth: an option present
 * there and absent here is shown and preserved.
 */
final class ServerIniSchema
{
    /** @var list<array{name: string, options: list<string>}> */
    public const GROUPS = [
        [
            'name' => 'Details',
            'options' => [
                'DefaultPort',
                'PublicName',
                'PublicDescription',
                'Public',
                'Password',
                'PauseEmpty',
                'ResetID',
            ],
        ],
        [
            'name' => 'Steam',
            'options' => [
                'UDPPort',
                'MaxAccountsPerUser',
                'SteamScoreboard',
            ],
        ],
        [
            'name' => 'Backups',
            'options' => [
                'BackupsCount',
                'BackupsOnStart',
                'BackupsOnVersionChange',
                'BackupsPeriod',
            ],
        ],
        [
            'name' => 'SteamWorkshop',
            'options' => [],
        ],
        [
            'name' => 'Mods',
            'options' => [],
        ],
        [
            'name' => 'Map',
            'options' => [],
        ],
        [
            'name' => 'SpawnRegions',
            'options' => [],
        ],
        [
            'name' => 'Players',
            'options' => [
                'MaxPlayers',
                'Open',
                'DropOffWhiteListAfterDeath',
                'DisplayUserName',
                'ShowFirstAndLastName',
                'SpawnItems',
                'PingLimit',
                'ServerPlayerID',
                'SleepAllowed',
                'SleepNeeded',
                'PlayerRespawnWithSelf',
                'PlayerRespawnWithOther',
                'RemovePlayerCorpsesOnCorpseRemoval',
                'TrashDeleteAll',
                'PVPMeleeWhileHitReaction',
                'MouseOverToSeeDisplayName',
                'UsernameDisguises',
                'HideDisguisedUserName',
                'HidePlayersBehindYou',
                'PlayerBumpPlayer',
                'MapRemotePlayerVisibility',
                'AllowCoop',
            ],
        ],
        [
            'name' => 'Admin',
            'options' => [
                'ClientCommandFilter',
                'ClientActionLogs',
                'PerkLogs',
                'DisableRadioStaff',
                'DisableRadioAdmin',
                'DisableRadioGM',
                'DisableRadioOverseer',
                'DisableRadioModerator',
                'DisableRadioInvisible',
            ],
        ],
        [
            'name' => 'Fire',
            'options' => [
                'NoFire',
            ],
        ],
        [
            'name' => 'PVP',
            'options' => [
                'PVP',
                'SafetySystem',
                'ShowSafety',
                'SafetyToggleTimer',
                'SafetyCooldownTimer',
                'PVPMeleeDamageModifier',
                'PVPFirearmDamageModifier',
            ],
        ],
        [
            'name' => 'Loot',
            'options' => [
                'SafehousePreventsLootRespawn',
                'ItemNumbersLimitPerContainer',
            ],
        ],
        [
            'name' => 'War',
            'options' => [
                'War',
                'WarStartDelay',
                'WarDuration',
                'WarSafehouseHitPoints',
            ],
        ],
        [
            'name' => 'Faction',
            'options' => [
                'Faction',
                'FactionDaySurvivedToCreate',
                'FactionPlayersRequiredForTag',
            ],
        ],
        [
            'name' => 'Safehouse',
            'options' => [
                'AdminSafehouse',
                'PlayerSafehouse',
                'SafehouseAllowTrepass',
                'SafehouseAllowFire',
                'SafehouseAllowLoot',
                'SafehouseAllowRespawn',
                'SafehouseDaySurvivedToClaim',
                'SafeHouseRemovalTime',
                'DisableSafehouseWhenOwnerConnected',
                'SafehouseAllowNonResidential',
                'SafehouseDisableDisguises',
            ],
        ],
        [
            'name' => 'Chat',
            'options' => [
                'GlobalChat',
                'AnnounceDeath',
                'AnnounceAnimalDeath',
                'ServerWelcomeMessage',
                'ChatMessageCharacterLimit',
                'ChatMessageSlowModeTime',
            ],
        ],
        [
            'name' => 'RCON',
            'options' => [
                'RCONPort',
                'RCONPassword',
            ],
        ],
        [
            'name' => 'Discord',
            'options' => [
                'DiscordEnable',
                'DiscordToken',
                'DiscordChatChannel',
                'DiscordLogChannel',
                'DiscordCommandChannel',
            ],
        ],
        [
            'name' => 'UPnP',
            'options' => [
                'UPnP',
            ],
        ],
        [
            'name' => 'Other',
            'options' => [
                'DoLuaChecksum',
                'AllowDestructionBySledgehammer',
                'SledgehammerOnlyInSafehouse',
                'SaveWorldEveryMinutes',
                'FastForwardMultiplier',
                'AllowNonAsciiUsername',
            ],
        ],
        [
            'name' => 'Vehicles',
            'options' => [
                'SpeedLimit',
            ],
        ],
        [
            'name' => 'Voice',
            'options' => [
                'VoiceEnable',
                'VoiceMinDistance',
                'VoiceMaxDistance',
                'Voice3D',
            ],
        ],
        [
            'name' => 'Advanced',
            'options' => [
                'PVPLogToolChat',
                'PVPLogToolFile',
                'ChatStreams',
                'SwitchZombiesOwnershipEachUpdate',
                'SpawnPoint',
                'SafetyDisconnectDelay',
                'Mods',
                'Map',
                'DenyLoginOnOverloadedServer',
                'MaxSafezoneSize',
                'WebhookAddress',
                'KnockedDownAllowed',
                'SneakModeHideFromOtherPlayers',
                'UltraSpeedDoesnotAffectToAnimals',
                'WorkshopItems',
                'SteamVAC',
                'LoginQueueEnabled',
                'LoginQueueConnectTimeout',
                'server_browser_announced_ip',
                'BloodSplatLifespanDays',
                'BanKickGlobalSound',
                'CarEngineAttractionModifier',
                'DisableVehicleTowing',
                'DisableTrailerTowing',
                'DisableBurntTowing',
                'BadWordListFile',
                'GoodWordListFile',
                'BadWordPolicy',
                'BadWordReplacement',
                'AntiCheatSafety',
                'AntiCheatSpeed',
                'AntiCheatNoClip',
                'AntiCheatHit',
                'AntiCheatPacketException',
                'AntiCheatPermission',
                'AntiCheatXP',
                'AntiCheatSafeHouse',
                'AntiCheatPlayer',
                'AntiCheatChecksum',
                'MultiplayerStatisticsPeriod',
                'DisableScoreboard',
                'HideAdminsInPlayerList',
                'MaxPacketsPerSecond',
                'ShowCoordinates',
                'Seed',
                'UsePhysicsHitReaction',
            ],
        ],
    ];

    /**
     * @var array<string, array{key: string, name: string, type: string|null,
     *     group: string, default: bool|float|int|string|null,
     *     min: float|int|null, max: float|int|null, numValues: int|null,
     *     tooltips: array<string, string|null>}>
     */
    public const OPTIONS = [
        'DefaultPort' => [
            'key' => 'DefaultPort',
            'name' => 'DefaultPort',
            'type' => 'integer',
            'group' => 'Details',
            'default' => 16261,
            'min' => 0,
            'max' => 65535,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Default starting port for player data. If UDP, this is this one of two ports used.',
                'DE' => 'Der UDP-Port mit dem sich die Spieler zum Server verbinden.',
            ],
        ],
        'PublicName' => [
            'key' => 'PublicName',
            'name' => 'PublicName',
            'type' => 'string',
            'group' => 'Details',
            'default' => 'My PZ Server',
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Name of the server displayed in the in-game browser and, if applicable, the Steam browser',
                'DE' => 'Wird im Server-Browser angezeigt und möglicherweise auch im Steam-Server-Browser',
            ],
        ],
        'PublicDescription' => [
            'key' => 'PublicDescription',
            'name' => 'PublicDescription',
            'type' => 'text',
            'group' => 'Details',
            'default' => NULL,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Description displayed in the in-game public server browser. Typing \\n will create a new line in your description',
                'DE' => 'Beschreibung wird im Server-Browser angezeigt. Mit \\n wird eine neue Zeile ihinzugefügt',
            ],
        ],
        'Public' => [
            'key' => 'Public',
            'name' => 'Public',
            'type' => 'boolean',
            'group' => 'Details',
            'default' => false,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Shows the server on the in-game browser. (Note: Steam-enabled servers are always visible in the Steam server browser)',
                'DE' => 'Listet den Server im Server-Browser. (Server mit Steam aktivierung werden auch im Steam-Server-Browser angezeigt)',
            ],
        ],
        'Password' => [
            'key' => 'Password',
            'name' => 'Password',
            'type' => 'string',
            'group' => 'Details',
            'default' => NULL,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Clients must know this password to join the server. (Ignored when hosting a server via the Host button)',
                'DE' => 'Spieler müssen das Passwort kennen um dem Server beizutreten.',
            ],
        ],
        'PauseEmpty' => [
            'key' => 'PauseEmpty',
            'name' => 'PauseEmpty',
            'type' => 'boolean',
            'group' => 'Details',
            'default' => true,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Game time stops when there are no players online',
                'DE' => 'Die Spielwelt-Zeit wird angehalten wenn sich kein Spieler auf dem Server befindet',
            ],
        ],
        'ResetID' => [
            'key' => 'ResetID',
            'name' => 'ResetID',
            'type' => 'integer',
            'group' => 'Details',
            'default' => NULL,
            'min' => 0,
            'max' => 2147483647,
            'numValues' => NULL,
            'defaultIsGenerated' => true,
            'tooltips' => [
                'EN' => 'Reset ID determines if the server has undergone a soft-reset. If this number does match the client, the client must create a new character. Used in conjunction with PlayerServerID. It is strongly advised that you backup these IDs somewhere',
                'DE' => 'Diese Nummer wird nach einem Soft-Reset geändert. Eine Änderung dieser Zahl löscht die Client-Sicherungsdateien (aber nicht Client-Spieler-Dateien).',
            ],
        ],
        'UDPPort' => [
            'key' => 'UDPPort',
            'name' => 'UDPPort',
            'type' => 'integer',
            'group' => 'Steam',
            'default' => 16262,
            'min' => 0,
            'max' => 65535,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => NULL,
                'DE' => NULL,
            ],
        ],
        'MaxAccountsPerUser' => [
            'key' => 'MaxAccountsPerUser',
            'name' => 'MaxAccountsPerUser',
            'type' => 'integer',
            'group' => 'Steam',
            'default' => 0,
            'min' => 0,
            'max' => 2147483647,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Limits the number of different accounts a single Steam user may create on this server. Ignored when using the Hosts button.',
                'DE' => 'Begrenzt die Anzahl der Konten die ein Steam Benutzer auf diesem Server erstellen darf. Wird ignoriert wenn es sich um einen über Steam gehosteten Server handelt.',
            ],
        ],
        'SteamScoreboard' => [
            'key' => 'SteamScoreboard',
            'name' => 'SteamScoreboard',
            'type' => 'boolean',
            'group' => 'Steam',
            'default' => false,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Show Steam usernames and avatars in the Players list.',
                'DE' => 'Steam-Benutzernamen und Avatare in der Spielerliste anzeigen.\\nAN: true\\nAUS: false\\nNUR ADMINS: admin',
            ],
        ],
        'BackupsCount' => [
            'key' => 'BackupsCount',
            'name' => 'BackupsCount',
            'type' => 'integer',
            'group' => 'Backups',
            'default' => 5,
            'min' => 1,
            'max' => 300,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => NULL,
                'DE' => NULL,
            ],
        ],
        'BackupsOnStart' => [
            'key' => 'BackupsOnStart',
            'name' => 'BackupsOnStart',
            'type' => 'boolean',
            'group' => 'Backups',
            'default' => true,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => NULL,
                'DE' => NULL,
            ],
        ],
        'BackupsOnVersionChange' => [
            'key' => 'BackupsOnVersionChange',
            'name' => 'BackupsOnVersionChange',
            'type' => 'boolean',
            'group' => 'Backups',
            'default' => true,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => NULL,
                'DE' => NULL,
            ],
        ],
        'BackupsPeriod' => [
            'key' => 'BackupsPeriod',
            'name' => 'BackupsPeriod',
            'type' => 'integer',
            'group' => 'Backups',
            'default' => 0,
            'min' => 0,
            'max' => 1500,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => NULL,
                'DE' => NULL,
            ],
        ],
        'MaxPlayers' => [
            'key' => 'MaxPlayers',
            'name' => 'MaxPlayers',
            'type' => 'integer',
            'group' => 'Players',
            'default' => 32,
            'min' => 1,
            'max' => 254,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Maximum number of players that can be on the server at one time. This excludes admins.<br>WARNING: Server player counts above 32 will potentially result in poor map streaming and desync. Please advance with caution.',
                'DE' => 'Maximale Anzahl von Spielern, die auf dem Server gleichzeitig sein können, ohne Admins. <br>WARNUNG: Server-Spielerzahlen über 32 führen möglicherweise zu schlechtem Karten-Streaming und Desynchronisation. Gehe bitte vorsichtig vor.',
            ],
        ],
        'Open' => [
            'key' => 'Open',
            'name' => 'Open',
            'type' => 'boolean',
            'group' => 'Players',
            'default' => true,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Clients may join without already having an account in the whitelist. If set to false, administrators must manually create username/password combos.',
                'DE' => 'Unregistrierte Spieler können sich mit dem Server verbinden.',
            ],
        ],
        'DropOffWhiteListAfterDeath' => [
            'key' => 'DropOffWhiteListAfterDeath',
            'name' => 'DropOffWhiteListAfterDeath',
            'type' => 'boolean',
            'group' => 'Players',
            'default' => false,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Remove player accounts from the whitelist after death. This prevents players creating a new character after death on Open=false servers',
                'DE' => 'Enfernt Spielerkonten aus der weißen Liste nach dem Tod. Verhindert einen neuen Charakter nach dem Tod zu erstellen.',
            ],
        ],
        'DisplayUserName' => [
            'key' => 'DisplayUserName',
            'name' => 'DisplayUserName',
            'type' => 'boolean',
            'group' => 'Players',
            'default' => true,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Display usernames above player\'s heads in-game.',
                'DE' => 'Zeigt den Benutzernamen über den Köpfen der Spieler an.',
            ],
        ],
        'ShowFirstAndLastName' => [
            'key' => 'ShowFirstAndLastName',
            'name' => 'ShowFirstAndLastName',
            'type' => 'boolean',
            'group' => 'Players',
            'default' => false,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Display first & last name above player\'s heads.',
                'DE' => 'Vor- und Nachnamen über Spielercharakteren anzeigen.',
            ],
        ],
        'SpawnItems' => [
            'key' => 'SpawnItems',
            'name' => 'SpawnItems',
            'type' => 'string',
            'group' => 'Players',
            'default' => NULL,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Item types new players spawn with.\\nSeparate multiple item types with commas.\\nExample: Base.Axe,Base.Bag_BigHikingBag',
                'DE' => 'Gegenstände mit dem neue Spieler spawnen.\\nMehrere Gegenstände mittels einem Komma trennen.\\nz.B.: Base.Axe, Base.BigHikingBag',
            ],
        ],
        'PingLimit' => [
            'key' => 'PingLimit',
            'name' => 'PingLimit',
            'type' => 'integer',
            'group' => 'Players',
            'default' => 0,
            'min' => 0,
            'max' => 2147483647,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Ping limit, in milliseconds, before a player is kicked from the server. (Set to 0 to disable)',
                'DE' => 'Der Ping-Limit in Millisekunden, bevor eine Spieler vom Server gekickt wird. Setze es auf 0, um es zu deaktivieren',
            ],
        ],
        'ServerPlayerID' => [
            'key' => 'ServerPlayerID',
            'name' => 'ServerPlayerID',
            'type' => 'string',
            'group' => 'Players',
            'default' => NULL,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => true,
            'tooltips' => [
                'EN' => 'ServerPlayerID determines if a character is from another server, or single player. This value may be changed by soft resets. If this number does match the client, the client must create a new character. This is used in conjunction with ResetID. It is strongly advised that you backup these IDs somewhere',
                'DE' => 'Wird in den Client-Spieler-Dateien geschrieben, so dass Spieler keine Sicherungsdateien von \'Einzelspieler\' oder einem anderen Server verwenden können.',
            ],
        ],
        'SleepAllowed' => [
            'key' => 'SleepAllowed',
            'name' => 'SleepAllowed',
            'type' => 'boolean',
            'group' => 'Players',
            'default' => false,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Players are allowed to sleep when their survivor becomes tired, but they do not NEED to sleep',
                'DE' => 'Die Spieler können zu jeder Zeit schlafen.',
            ],
        ],
        'SleepNeeded' => [
            'key' => 'SleepNeeded',
            'name' => 'SleepNeeded',
            'type' => 'boolean',
            'group' => 'Players',
            'default' => false,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Players get tired and need to sleep. (Ignored if SleepAllowed=false)',
                'DE' => 'Spieler werden müde und müssen schlafen.  Wird ignoriert, wenn SleepAllowed: false',
            ],
        ],
        'PlayerRespawnWithSelf' => [
            'key' => 'PlayerRespawnWithSelf',
            'name' => 'PlayerRespawnWithSelf',
            'type' => 'boolean',
            'group' => 'Players',
            'default' => false,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Players can respawn in-game at the coordinates where they died',
                'DE' => 'Die Spieler können im Spiel respawnen, wo sie starben.',
            ],
        ],
        'PlayerRespawnWithOther' => [
            'key' => 'PlayerRespawnWithOther',
            'name' => 'PlayerRespawnWithOther',
            'type' => 'boolean',
            'group' => 'Players',
            'default' => false,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Players can respawn in-game at a split screen / Remote Play player\'s location',
                'DE' => 'Die Spieler können auf einem geteilten Bildschirm, beim Mitspieler respawnen.',
            ],
        ],
        'RemovePlayerCorpsesOnCorpseRemoval' => [
            'key' => 'RemovePlayerCorpsesOnCorpseRemoval',
            'name' => 'RemovePlayerCorpsesOnCorpseRemoval',
            'type' => 'boolean',
            'group' => 'Players',
            'default' => false,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'If enabled, when HoursForCorpseRemoval triggers, it will also remove player\'s corpses from the ground.',
                'DE' => 'Bei TRUE (AN). Wenn HoursForCorpseRemoval ausgelöst wird, wird es auch die Leichen der Spieler entfernen.',
            ],
        ],
        'TrashDeleteAll' => [
            'key' => 'TrashDeleteAll',
            'name' => 'TrashDeleteAll',
            'type' => 'boolean',
            'group' => 'Players',
            'default' => false,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'If true, player can use the "delete all" button on bins.',
                'DE' => 'Wenn aktiv, kann der Spieler den Button Alles löschen für Mülleimer verwenden.',
            ],
        ],
        'PVPMeleeWhileHitReaction' => [
            'key' => 'PVPMeleeWhileHitReaction',
            'name' => 'PVPMeleeWhileHitReaction',
            'type' => 'boolean',
            'group' => 'Players',
            'default' => false,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'If true, player can hit again when struck by another player.',
                'DE' => 'Wenn aktiv, kann ein Spieler zuschlagen, während er von einem anderen Spieler getroffen wird.',
            ],
        ],
        'MouseOverToSeeDisplayName' => [
            'key' => 'MouseOverToSeeDisplayName',
            'name' => 'MouseOverToSeeDisplayName',
            'type' => 'boolean',
            'group' => 'Players',
            'default' => true,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'If true, players will have to mouse over someone to see their display name.',
                'DE' => 'Wenn aktiv, muss mit der Maus über einen Spielercharakter gezielt werden, um den Spielernamen anzuzeigen.',
            ],
        ],
        'UsernameDisguises' => [
            'key' => 'UsernameDisguises',
            'name' => 'UsernameDisguises',
            'type' => 'boolean',
            'group' => 'Players',
            'default' => false,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => NULL,
                'DE' => NULL,
            ],
        ],
        'HideDisguisedUserName' => [
            'key' => 'HideDisguisedUserName',
            'name' => 'HideDisguisedUserName',
            'type' => 'boolean',
            'group' => 'Players',
            'default' => false,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => NULL,
                'DE' => NULL,
            ],
        ],
        'HidePlayersBehindYou' => [
            'key' => 'HidePlayersBehindYou',
            'name' => 'HidePlayersBehindYou',
            'type' => 'boolean',
            'group' => 'Players',
            'default' => true,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'If true, automatically hide the player you can\'t see (like zombies).',
                'DE' => 'Wenn aktiv, verschwinden Spielercharaktere außerhalb des Sichtfelds des Spielers (wie Zombies).',
            ],
        ],
        'PlayerBumpPlayer' => [
            'key' => 'PlayerBumpPlayer',
            'name' => 'PlayerBumpPlayer',
            'type' => 'boolean',
            'group' => 'Players',
            'default' => false,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Governs whether players bump (and knock over) other players when running through them.',
                'DE' => 'Spieler stoßen/schieben andere Spieler, wenn sie durch sie hindurchlaufen.',
            ],
        ],
        'MapRemotePlayerVisibility' => [
            'key' => 'MapRemotePlayerVisibility',
            'name' => 'MapRemotePlayerVisibility',
            'type' => 'integer',
            'group' => 'Players',
            'default' => 1,
            'min' => 1,
            'max' => 4,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Controls display of remote players on the in-game map.\\n1=Hidden 2=Friends 3=Friends and nearby players 4=Everyone',
                'DE' => 'Steuert die Anzeige von anderen Spielern auf der Karte im Spiel.\\n1',
            ],
        ],
        'AllowCoop' => [
            'key' => 'AllowCoop',
            'name' => 'AllowCoop',
            'type' => 'boolean',
            'group' => 'Players',
            'default' => true,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Allow co-op/splitscreen players',
                'DE' => 'Koop-/Splitscreen-Spieler zulassen',
            ],
        ],
        'ClientCommandFilter' => [
            'key' => 'ClientCommandFilter',
            'name' => 'ClientCommandFilter',
            'type' => 'string',
            'group' => 'Admin',
            'default' => '-vehicle.*;+vehicle.damageWindow;+vehicle.fixPart;+vehicle.installPart;+vehicle.uninstallPart',
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Semicolon-separated list of commands that will not be written to the cmd.txt server log. For example: \\n-vehicle. Inputting * means do NOT write any vehicle command. Inputting: \\n+vehicle.installPart means DO write that command',
                'DE' => 'Semikolon-getrennte Liste von Befehlen, die nicht in die cmd.txt-Serverprotokoll geschrieben werden.\\n-.vehicle.* bedeutet, dass kein Fahrzeugbefehl geschrieben wird.\\n+vehicle.installPart bedeutet, dass dieser Befehl geschrieben wird.',
            ],
        ],
        'ClientActionLogs' => [
            'key' => 'ClientActionLogs',
            'name' => 'ClientActionLogs',
            'type' => 'string',
            'group' => 'Admin',
            'default' => 'ISEnterVehicle;ISExitVehicle;ISTakeEngineParts;',
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Semicolon-separated list of actions that will be written to the ClientActionLogs.txt server log.',
                'DE' => 'Strichpunkt getrennte Liste von Aktionen, die in das Serverprotokoll ClientActionLogs.txt geschrieben werden.',
            ],
        ],
        'PerkLogs' => [
            'key' => 'PerkLogs',
            'name' => 'PerkLogs',
            'type' => 'boolean',
            'group' => 'Admin',
            'default' => true,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Track changes in player perk levels in PerkLog.txt server log',
                'DE' => 'Zeichne Änderungen an den Vorteilstufen der Spieler PerkLog.txt-Serverprotokoll auf',
            ],
        ],
        'DisableRadioStaff' => [
            'key' => 'DisableRadioStaff',
            'name' => 'DisableRadioStaff',
            'type' => 'boolean',
            'group' => 'Admin',
            'default' => false,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Disables radio transmissions from players with an access level',
                'DE' => 'Deaktiviert die Funkübertragungen von Spielern mit beliebiger Zugriffsstufe.',
            ],
        ],
        'DisableRadioAdmin' => [
            'key' => 'DisableRadioAdmin',
            'name' => 'DisableRadioAdmin',
            'type' => 'boolean',
            'group' => 'Admin',
            'default' => true,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Disables radio transmissions from players with \'admin\' access level',
                'DE' => 'Deaktiviert die Funkübertragungen von Spielern mit der Zugriffsstufe \'admin\'.',
            ],
        ],
        'DisableRadioGM' => [
            'key' => 'DisableRadioGM',
            'name' => 'DisableRadioGM',
            'type' => 'boolean',
            'group' => 'Admin',
            'default' => true,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Disables radio transmissions from players with \'gm\' access level',
                'DE' => 'Deaktiviert die Funkübertragungen von Spielern mit der Zugriffsstufe \'gm\'.',
            ],
        ],
        'DisableRadioOverseer' => [
            'key' => 'DisableRadioOverseer',
            'name' => 'DisableRadioOverseer',
            'type' => 'boolean',
            'group' => 'Admin',
            'default' => false,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Disables radio transmissions from players with \'overseer\' access level',
                'DE' => 'Deaktiviert die Funkübertragungen von Spielern mit der Zugriffsstufe \'overseer\'.',
            ],
        ],
        'DisableRadioModerator' => [
            'key' => 'DisableRadioModerator',
            'name' => 'DisableRadioModerator',
            'type' => 'boolean',
            'group' => 'Admin',
            'default' => false,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Disables radio transmissions from players with \'moderator\' access level',
                'DE' => 'Deaktiviert die Funkübertragungen von Spielern mit der Zugriffsstufe \'moderator\'.',
            ],
        ],
        'DisableRadioInvisible' => [
            'key' => 'DisableRadioInvisible',
            'name' => 'DisableRadioInvisible',
            'type' => 'boolean',
            'group' => 'Admin',
            'default' => true,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Disables radio transmissions from invisible players',
                'DE' => 'Deaktiviert Funkübertragungen von unsichtbaren Spielern.',
            ],
        ],
        'NoFire' => [
            'key' => 'NoFire',
            'name' => 'NoFire',
            'type' => 'boolean',
            'group' => 'Fire',
            'default' => false,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'All forms of fire are disabled - except for campfires',
                'DE' => 'Alle arten von Feuer sind deaktiviert, ausgenommen Lagerfeuer',
            ],
        ],
        'PVP' => [
            'key' => 'PVP',
            'name' => 'PVP',
            'type' => 'boolean',
            'group' => 'PVP',
            'default' => true,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Players can hurt and kill other players',
                'DE' => 'Die Spieler können andere Spieler verletzten.',
            ],
        ],
        'SafetySystem' => [
            'key' => 'SafetySystem',
            'name' => 'SafetySystem',
            'type' => 'boolean',
            'group' => 'PVP',
            'default' => true,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Players can enter and leave PVP on an individual basis. A player can only hurt another player when at least one of them is in PVP mode - as shown by the unobscured skull and crossbones on the left of the screen. When SafetySystem=false, players are free to hurt each other at any time if PVP is enabled.',
                'DE' => 'Die Spieler können PVP-Modus einzeln betreten und verlassen. Ein Spieler kann einen anderen Spieler nur verletzen, wenn ein oder beide Spieler im PvP-Modus befinden. Wenn SafetySystem',
            ],
        ],
        'ShowSafety' => [
            'key' => 'ShowSafety',
            'name' => 'ShowSafety',
            'type' => 'boolean',
            'group' => 'PVP',
            'default' => true,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Display a skull icon over the head of players who have entered PVP mode',
                'DE' => 'Zeigt ein Totenschädel-Symbol über die Köpfe der Spieler, die sich im PVP-Modus befinden.',
            ],
        ],
        'SafetyToggleTimer' => [
            'key' => 'SafetyToggleTimer',
            'name' => 'SafetyToggleTimer',
            'type' => 'integer',
            'group' => 'PVP',
            'default' => 2,
            'min' => 0,
            'max' => 1000,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'The time it takes for a player to enter and leave PVP mode',
                'DE' => 'Die Zeit die ein Spieler zum betreten oder verlassen des PVP-Modus braucht.',
            ],
        ],
        'SafetyCooldownTimer' => [
            'key' => 'SafetyCooldownTimer',
            'name' => 'SafetyCooldownTimer',
            'type' => 'integer',
            'group' => 'PVP',
            'default' => 3,
            'min' => 0,
            'max' => 1000,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'The delay before a player can enter or leave PVP mode again, having recently done so',
                'DE' => 'Die Verzögerung bevor ein Spieler wieder den PVP-Modus betreten oder verlassen kann.',
            ],
        ],
        'PVPMeleeDamageModifier' => [
            'key' => 'PVPMeleeDamageModifier',
            'name' => 'PVPMeleeDamageModifier',
            'type' => 'double',
            'group' => 'PVP',
            'default' => 30.0,
            'min' => 0.0,
            'max' => 500.0,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Damage multiplier for PVP melee attacks.',
                'DE' => 'Schadensmultiplikator für PVP-Nahkampfangriffe',
            ],
        ],
        'PVPFirearmDamageModifier' => [
            'key' => 'PVPFirearmDamageModifier',
            'name' => 'PVPFirearmDamageModifier',
            'type' => 'double',
            'group' => 'PVP',
            'default' => 50.0,
            'min' => 0.0,
            'max' => 500.0,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Damage multiplier for PVP ranged attacks.',
                'DE' => 'Schadensmultiplikator für PVP-Fernkampfangriffe',
            ],
        ],
        'SafehousePreventsLootRespawn' => [
            'key' => 'SafehousePreventsLootRespawn',
            'name' => 'SafehousePreventsLootRespawn',
            'type' => 'boolean',
            'group' => 'Loot',
            'default' => true,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Items will not respawn in buildings that players have claimed as a safehouse',
                'DE' => 'Gegenstände respawnen nicht in Gebäuden, die Spieler als Versteck markiert haben',
            ],
        ],
        'ItemNumbersLimitPerContainer' => [
            'key' => 'ItemNumbersLimitPerContainer',
            'name' => 'ItemNumbersLimitPerContainer',
            'type' => 'integer',
            'group' => 'Loot',
            'default' => 0,
            'min' => 0,
            'max' => 9000,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Maximum number of items that can be placed in a container.  Zero means there is no limit. (PLEASE NOTE: This includes individual small items such as nails. A limit of 50 will mean only 50 nails can be stored.)',
                'DE' => 'Maximale Anzahl von Gegenständen, die in einem Behälter gelegt werden können. Null bedeutet keine Begrenzung.',
            ],
        ],
        'War' => [
            'key' => 'War',
            'name' => 'War',
            'type' => 'boolean',
            'group' => 'War',
            'default' => false,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => NULL,
                'DE' => NULL,
            ],
        ],
        'WarStartDelay' => [
            'key' => 'WarStartDelay',
            'name' => 'WarStartDelay',
            'type' => 'integer',
            'group' => 'War',
            'default' => 600,
            'min' => 60,
            'max' => 2147483647,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Time in seconds before the war starts.',
                'DE' => 'Zeit in Sekunden, bevor der Krieg beginnt.',
            ],
        ],
        'WarDuration' => [
            'key' => 'WarDuration',
            'name' => 'WarDuration',
            'type' => 'integer',
            'group' => 'War',
            'default' => 3600,
            'min' => 60,
            'max' => 2147483647,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'War duration in seconds.',
                'DE' => 'Kriegsdauer in Sekunden.',
            ],
        ],
        'WarSafehouseHitPoints' => [
            'key' => 'WarSafehouseHitPoints',
            'name' => 'WarSafehouseHitPoints',
            'type' => 'integer',
            'group' => 'War',
            'default' => 3,
            'min' => 0,
            'max' => 2147483647,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Safehouse hit points limit.',
                'DE' => 'Trefferpunkt-Limit eines Verstecks.',
            ],
        ],
        'Faction' => [
            'key' => 'Faction',
            'name' => 'Faction',
            'type' => 'boolean',
            'group' => 'Faction',
            'default' => true,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Players can create factions when true',
                'DE' => 'Wenn es TRUE (AN) ist, wird den Spielern erlaubt, Fraktionen/Gruppen zu bilden.',
            ],
        ],
        'FactionDaySurvivedToCreate' => [
            'key' => 'FactionDaySurvivedToCreate',
            'name' => 'FactionDaySurvivedToCreate',
            'type' => 'integer',
            'group' => 'Faction',
            'default' => 0,
            'min' => 0,
            'max' => 2147483647,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Players must survive this number of in-game days before being allowed to create a faction',
                'DE' => 'Du musst X Tage überleben, bevor du eine Fraktionen/Gruppe erschaffen kannst.',
            ],
        ],
        'FactionPlayersRequiredForTag' => [
            'key' => 'FactionPlayersRequiredForTag',
            'name' => 'FactionPlayersRequiredForTag',
            'type' => 'integer',
            'group' => 'Faction',
            'default' => 1,
            'min' => 1,
            'max' => 2147483647,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Number of players required as faction members before the faction owner can create a group tag',
                'DE' => 'Wieviele Spieler sind nötig, bevor der Fraktions/-Gruppenbesitzer ein spezielles Tag erstellen kann.',
            ],
        ],
        'AdminSafehouse' => [
            'key' => 'AdminSafehouse',
            'name' => 'AdminSafehouse',
            'type' => 'boolean',
            'group' => 'Safehouse',
            'default' => false,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Only admins can claim safehouses',
                'DE' => 'Administratoren können ein Versteck beanspruchen.',
            ],
        ],
        'PlayerSafehouse' => [
            'key' => 'PlayerSafehouse',
            'name' => 'PlayerSafehouse',
            'type' => 'boolean',
            'group' => 'Safehouse',
            'default' => false,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Both admins and players can claim safehouses',
                'DE' => 'Nicht-Administratoren können eine Versteck beanspruchen.',
            ],
        ],
        'SafehouseAllowTrepass' => [
            'key' => 'SafehouseAllowTrepass',
            'name' => 'SafehouseAllowTrepass',
            'type' => 'boolean',
            'group' => 'Safehouse',
            'default' => true,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Allow non-members to enter a safehouse without being invited',
                'DE' => 'Erlaubt Nicht-Mitgliedern das Versteck zu betreten.',
            ],
        ],
        'SafehouseAllowFire' => [
            'key' => 'SafehouseAllowFire',
            'name' => 'SafehouseAllowFire',
            'type' => 'boolean',
            'group' => 'Safehouse',
            'default' => true,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Allow fire to damage safehouses',
                'DE' => 'Das Versteck kann durch Feuer schaden nehmen.',
            ],
        ],
        'SafehouseAllowLoot' => [
            'key' => 'SafehouseAllowLoot',
            'name' => 'SafehouseAllowLoot',
            'type' => 'boolean',
            'group' => 'Safehouse',
            'default' => true,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Allow non-members to take items from safehouses',
                'DE' => 'Erlaubt Nicht-Mitgliedern eines Verstecks, Gegenstände zu entnehmen.',
            ],
        ],
        'SafehouseAllowRespawn' => [
            'key' => 'SafehouseAllowRespawn',
            'name' => 'SafehouseAllowRespawn',
            'type' => 'boolean',
            'group' => 'Safehouse',
            'default' => false,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Players will respawn in a safehouse that they were a member of before they died',
                'DE' => 'Spieler spawnen im Versteck das beansprucht wurde, bevor sie starben.',
            ],
        ],
        'SafehouseDaySurvivedToClaim' => [
            'key' => 'SafehouseDaySurvivedToClaim',
            'name' => 'SafehouseDaySurvivedToClaim',
            'type' => 'integer',
            'group' => 'Safehouse',
            'default' => 0,
            'min' => 0,
            'max' => 2147483647,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Players must have survived this number of in-game days before they are allowed to claim a safehouse',
                'DE' => 'Spieler müssen so viele Spielwelt-Tage überlebt haben, bevor sie ein Versteck beanspruchen können.',
            ],
        ],
        'SafeHouseRemovalTime' => [
            'key' => 'SafeHouseRemovalTime',
            'name' => 'SafeHouseRemovalTime',
            'type' => 'integer',
            'group' => 'Safehouse',
            'default' => 144,
            'min' => 0,
            'max' => 2147483647,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Players are automatically removed from a safehouse they have not visited for this many real-world hours',
                'DE' => 'Spieler werden automatisch aus einem Versteck entfernt, wenn diese nicht innerhalb der Echtzeit-Stunden das Versteck besucht haben.',
            ],
        ],
        'DisableSafehouseWhenOwnerConnected' => [
            'key' => 'DisableSafehouseWhenOwnerConnected',
            'name' => 'DisableSafehouseWhenOwnerConnected',
            'type' => 'boolean',
            'group' => 'Safehouse',
            'default' => false,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Safehouse acts like a normal house if an owner of the safehouse is connected (so secure when the owner is offline)',
                'DE' => 'Das Safehouse verhält sich wie ein normales Haus, wenn der Besitzer des Safehouses online ist (ist also sicher, wenn der Besitzer offline ist)',
            ],
        ],
        'SafehouseAllowNonResidential' => [
            'key' => 'SafehouseAllowNonResidential',
            'name' => 'SafehouseAllowNonResidential',
            'type' => 'boolean',
            'group' => 'Safehouse',
            'default' => false,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Governs whether players can claim non-residential buildings.',
                'DE' => 'Regelt ob Spieler Nichtwohngebäude beanspruchen können.',
            ],
        ],
        'SafehouseDisableDisguises' => [
            'key' => 'SafehouseDisableDisguises',
            'name' => 'SafehouseDisableDisguises',
            'type' => 'boolean',
            'group' => 'Safehouse',
            'default' => true,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => NULL,
                'DE' => NULL,
            ],
        ],
        'GlobalChat' => [
            'key' => 'GlobalChat',
            'name' => 'GlobalChat',
            'type' => 'boolean',
            'group' => 'Chat',
            'default' => true,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Toggles global chat on or off.',
                'DE' => 'Schaltet den globalen Chat ein oder aus.',
            ],
        ],
        'AnnounceDeath' => [
            'key' => 'AnnounceDeath',
            'name' => 'AnnounceDeath',
            'type' => 'boolean',
            'group' => 'Chat',
            'default' => false,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'If checked, every time a player dies a global message will be displayed in the chat',
                'DE' => 'Wenn aktiv, jedes Mal wenn ein Spieler stirbt wird eine Nachricht im Chat angezeigt',
            ],
        ],
        'AnnounceAnimalDeath' => [
            'key' => 'AnnounceAnimalDeath',
            'name' => 'AnnounceAnimalDeath',
            'type' => 'boolean',
            'group' => 'Chat',
            'default' => false,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'If checked, every time an animal dies a global message will be displayed in the chat',
                'DE' => 'Wenn aktiv, jedes Mal wenn ein Tier stirbt wird eine Nachricht im Chat angezeigt',
            ],
        ],
        'ServerWelcomeMessage' => [
            'key' => 'ServerWelcomeMessage',
            'name' => 'ServerWelcomeMessage',
            'type' => 'text',
            'group' => 'Chat',
            'default' => 'Welcome to Project Zomboid Multiplayer! <LINE> <LINE> To interact with the Chat panel: press Tab, T, or Enter. <LINE> <LINE> The Tab key will change the target stream of the message. <LINE> <LINE> Global Streams: /all <LINE> Local Streams: /say, /yell <LINE> Special Steams: /whisper, /safehouse, /faction. <LINE> <LINE> Press the Up arrow to cycle through your message history. Click the Gear icon to customize chat. <LINE> <LINE> Happy surviving!',
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'The first welcome message visible in the chat panel. This will be displayed immediately after player login. you can use RGB colours to chance the colour of the welcome message. You can also use < LINE>, without the space, to create a separate lines within your text. Use: \\<RGB:1,0,0> This message will show up red!',
                'DE' => 'Die erste Nachricht die im Chat-Panel sichtbar wird, sobald sich ein Spieler angemeldet hat. Du kannst RGB Farben nutzen um die Nachricht anzupassen, darüber hinaus kannst du < LINE> (ohne Leerzeichen) nutzen um Linien zu teilen. Mit \\<RGB:1,0,0> Wird diese Nachricht rot dargestellt!',
            ],
        ],
        'ChatMessageCharacterLimit' => [
            'key' => 'ChatMessageCharacterLimit',
            'name' => 'ChatMessageCharacterLimit',
            'type' => 'integer',
            'group' => 'Chat',
            'default' => 200,
            'min' => 64,
            'max' => 1024,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => NULL,
                'DE' => NULL,
            ],
        ],
        'ChatMessageSlowModeTime' => [
            'key' => 'ChatMessageSlowModeTime',
            'name' => 'ChatMessageSlowModeTime',
            'type' => 'integer',
            'group' => 'Chat',
            'default' => 3,
            'min' => 1,
            'max' => 30,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => NULL,
                'DE' => NULL,
            ],
        ],
        'RCONPort' => [
            'key' => 'RCONPort',
            'name' => 'RCONPort',
            'type' => 'integer',
            'group' => 'RCON',
            'default' => 27015,
            'min' => 0,
            'max' => 65535,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'The port for the RCON (Remote Console)',
                'DE' => 'Der Port für das RCON (Remote Console)',
            ],
        ],
        'RCONPassword' => [
            'key' => 'RCONPassword',
            'name' => 'RCONPassword',
            'type' => 'string',
            'group' => 'RCON',
            'default' => NULL,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'RCON password (Pick a strong password)',
                'DE' => 'RCON Passwort (Wähle ein starkes Passwort)',
            ],
        ],
        'DiscordEnable' => [
            'key' => 'DiscordEnable',
            'name' => 'DiscordEnable',
            'type' => 'boolean',
            'group' => 'Discord',
            'default' => false,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Enables global text chat integration with a Discord channel',
                'DE' => 'Aktiviert globalen Text Chat integration mit einem Discord Chat',
            ],
        ],
        'DiscordToken' => [
            'key' => 'DiscordToken',
            'name' => 'DiscordToken',
            'type' => 'string',
            'group' => 'Discord',
            'default' => NULL,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Discord bot access token',
                'DE' => 'Discord Bot-Zugriffstoken',
            ],
        ],
        'DiscordChatChannel' => [
            'key' => 'DiscordChatChannel',
            'name' => 'DiscordChatChannel',
            'type' => 'string',
            'group' => 'Discord',
            'default' => NULL,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'The Discord chat channel name',
                'DE' => 'Der Name des Discord Chats',
            ],
        ],
        'DiscordLogChannel' => [
            'key' => 'DiscordLogChannel',
            'name' => 'DiscordLogChannel',
            'type' => 'string',
            'group' => 'Discord',
            'default' => NULL,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'The Discord logs channel name',
                'DE' => 'Der Name des Discord-Protokollkanals',
            ],
        ],
        'DiscordCommandChannel' => [
            'key' => 'DiscordCommandChannel',
            'name' => 'DiscordCommandChannel',
            'type' => 'string',
            'group' => 'Discord',
            'default' => NULL,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'The Discord commands channel name',
                'DE' => 'Der Discord-Befehlskanalname',
            ],
        ],
        'UPnP' => [
            'key' => 'UPnP',
            'name' => 'UPnP',
            'type' => 'boolean',
            'group' => 'UPnP',
            'default' => true,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Attempt to configure a UPnP-enabled internet gateway to automatically setup port forwarding rules. The server will fall back to default ports if this fails',
                'DE' => 'Versuche Port-Weiterleitungsregeln an einem UPnP fähigen Internet-Gateway automatisch zu konfigurieren.',
            ],
        ],
        'DoLuaChecksum' => [
            'key' => 'DoLuaChecksum',
            'name' => 'DoLuaChecksum',
            'type' => 'boolean',
            'group' => 'Other',
            'default' => true,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Kick clients whose game files don\'t match the server\'s.',
                'DE' => 'Kickt Spieler, deren Spiel-Dateien nicht mit dem  des Servers übereinstimmen.',
            ],
        ],
        'AllowDestructionBySledgehammer' => [
            'key' => 'AllowDestructionBySledgehammer',
            'name' => 'AllowDestructionBySledgehammer',
            'type' => 'boolean',
            'group' => 'Other',
            'default' => true,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Allow players to destroy world objects with sledgehammers',
                'DE' => 'Welt-Objekte können mit einem Vorschlaghammer zerstört werden.',
            ],
        ],
        'SledgehammerOnlyInSafehouse' => [
            'key' => 'SledgehammerOnlyInSafehouse',
            'name' => 'SledgehammerOnlyInSafehouse',
            'type' => 'boolean',
            'group' => 'Other',
            'default' => false,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Allow players to destroy world objects only in their safehouse (require AllowDestructionBySledgehammer to true).',
                'DE' => 'Erlaube Spielern, Objekte nur in ihrem Unterschlupf zu zerstören (erfordere AllowDestructionBySledgehammer auf true).',
            ],
        ],
        'SaveWorldEveryMinutes' => [
            'key' => 'SaveWorldEveryMinutes',
            'name' => 'SaveWorldEveryMinutes',
            'type' => 'integer',
            'group' => 'Other',
            'default' => 0,
            'min' => 0,
            'max' => 2147483647,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Loaded parts of the map are saved after this set number of real-world minutes have passed. (The map is usually saved only after clients leave a loaded area)',
                'DE' => 'Geladene Teile der Karte werden gespeichert, nachdem die angegebenen Echtzeit-Minuten vergangen sind. In der Regel wird die Karte gespeichert, nachdem der Spieler einen geladenen Bereich verlassen hat.',
            ],
        ],
        'FastForwardMultiplier' => [
            'key' => 'FastForwardMultiplier',
            'name' => 'FastForwardMultiplier',
            'type' => 'double',
            'group' => 'Other',
            'default' => 40.0,
            'min' => 1.0,
            'max' => 100.0,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Governs how fast time passes while players sleep. Value multiplies the speed of the time that passes during sleeping.',
                'DE' => 'Wie schnell vergeht die Zeit, wenn alle schlafen?',
            ],
        ],
        'AllowNonAsciiUsername' => [
            'key' => 'AllowNonAsciiUsername',
            'name' => 'AllowNonAsciiUsername',
            'type' => 'boolean',
            'group' => 'Other',
            'default' => false,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Allow use of non-ASCII (cyrillic etc) characters in usernames',
                'DE' => 'Die Verwendung von nicht-ASCII (kyrillischen...) Zeichen im Benutzernamen ist erlaubt oder nicht.',
            ],
        ],
        'SpeedLimit' => [
            'key' => 'SpeedLimit',
            'name' => 'SpeedLimit',
            'type' => 'double',
            'group' => 'Vehicles',
            'default' => 70.0,
            'min' => 10.0,
            'max' => 150.0,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => NULL,
                'DE' => NULL,
            ],
        ],
        'VoiceEnable' => [
            'key' => 'VoiceEnable',
            'name' => 'VoiceEnable',
            'type' => 'boolean',
            'group' => 'Voice',
            'default' => true,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'VOIP is enabled when checked',
                'DE' => 'Wenn TRUE (AN), Sprachchat ist aktiviert.',
            ],
        ],
        'VoiceMinDistance' => [
            'key' => 'VoiceMinDistance',
            'name' => 'VoiceMinDistance',
            'type' => 'double',
            'group' => 'Voice',
            'default' => 10.0,
            'min' => 0.0,
            'max' => 100000.0,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'The minimum tile distance over which VOIP sounds can be heard.',
                'DE' => 'Die minimale Entfernung in Feldern, über die der Sprachchat zu hören ist.',
            ],
        ],
        'VoiceMaxDistance' => [
            'key' => 'VoiceMaxDistance',
            'name' => 'VoiceMaxDistance',
            'type' => 'double',
            'group' => 'Voice',
            'default' => 100.0,
            'min' => 0.0,
            'max' => 100000.0,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'The maximum tile distance over which VOIP sounds can be heard.',
                'DE' => 'Die maximale Entfernung in Feldern, über die der Sprachchat zu hören ist.',
            ],
        ],
        'Voice3D' => [
            'key' => 'Voice3D',
            'name' => 'Voice3D',
            'type' => 'boolean',
            'group' => 'Voice',
            'default' => true,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Toggle directional audio for VOIP',
                'DE' => 'Richtungs-Audio für den Sprachchat.',
            ],
        ],
        'PVPLogToolChat' => [
            'key' => 'PVPLogToolChat',
            'name' => 'PVPLogToolChat',
            'type' => 'boolean',
            'group' => 'Advanced',
            'default' => true,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'PVP is logged to admin chat',
                'DE' => 'PvP ist mit Admin-Chat verbunden',
            ],
        ],
        'PVPLogToolFile' => [
            'key' => 'PVPLogToolFile',
            'name' => 'PVPLogToolFile',
            'type' => 'boolean',
            'group' => 'Advanced',
            'default' => true,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'PVP is logged to file',
                'DE' => 'PvP ist mit Datei verbunden',
            ],
        ],
        'ChatStreams' => [
            'key' => 'ChatStreams',
            'name' => 'ChatStreams',
            'type' => 'string',
            'group' => 'Advanced',
            'default' => 's,r,a,w,y,sh,f,all',
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => NULL,
                'DE' => NULL,
            ],
        ],
        'SwitchZombiesOwnershipEachUpdate' => [
            'key' => 'SwitchZombiesOwnershipEachUpdate',
            'name' => 'SwitchZombiesOwnershipEachUpdate',
            'type' => 'boolean',
            'group' => 'Advanced',
            'default' => false,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => NULL,
                'DE' => NULL,
            ],
        ],
        'SpawnPoint' => [
            'key' => 'SpawnPoint',
            'name' => 'SpawnPoint',
            'type' => 'string',
            'group' => 'Advanced',
            'default' => '0,0,0',
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Force every new player to spawn at these set x,y,z world coordinates. Find desired coordinates at map.projectzomboid.com. (Ignored when 0,0,0)',
                'DE' => 'Jeden neuen Spieler bei den angebenen Weltkoordinaten \'x,y,z\' spawnen lassen. Wird ignoriert wenn: 0,0,0',
            ],
        ],
        'SafetyDisconnectDelay' => [
            'key' => 'SafetyDisconnectDelay',
            'name' => 'SafetyDisconnectDelay',
            'type' => 'integer',
            'group' => 'Advanced',
            'default' => 60,
            'min' => 0,
            'max' => 60,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => NULL,
                'DE' => NULL,
            ],
        ],
        'Mods' => [
            'key' => 'Mods',
            'name' => 'Mods',
            'type' => 'string',
            'group' => 'Advanced',
            'default' => NULL,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Enter the mod loading ID here. It can be found in \\Steam\\steamapps\\workshop\\modID\\mods\\modName\\info.txt',
                'DE' => 'Gib hier die Mod-Lade-ID ein. Diese kann gefunden werden unter: \\Steam\\steamapps\\workshop\\modID\\mods\\modName\\info.txt',
            ],
        ],
        'Map' => [
            'key' => 'Map',
            'name' => 'Map',
            'type' => 'string',
            'group' => 'Advanced',
            'default' => 'Muldraugh, KY',
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Enter the foldername of the mod found in \\Steam\\steamapps\\workshop\\modID\\mods\\modName\\media\\maps\\',
                'DE' => 'Gib hier den Ordnernamen der Mod ein wo diese zu finden ist. - \\Steam\\steamapps\\workshop\\modID\\mods\\modName\\media\\maps\\',
            ],
        ],
        'DenyLoginOnOverloadedServer' => [
            'key' => 'DenyLoginOnOverloadedServer',
            'name' => 'DenyLoginOnOverloadedServer',
            'type' => 'boolean',
            'group' => 'Advanced',
            'default' => true,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => NULL,
                'DE' => NULL,
            ],
        ],
        'MaxSafezoneSize' => [
            'key' => 'MaxSafezoneSize',
            'name' => 'MaxSafezoneSize',
            'type' => 'integer',
            'group' => 'Advanced',
            'default' => 20000,
            'min' => 0,
            'max' => 2147483647,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => NULL,
                'DE' => NULL,
            ],
        ],
        'WebhookAddress' => [
            'key' => 'WebhookAddress',
            'name' => 'WebhookAddress',
            'type' => 'string',
            'group' => 'Advanced',
            'default' => NULL,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'The Slack incoming webhook URL',
                'DE' => 'Die Slack-Webhook-URL',
            ],
        ],
        'KnockedDownAllowed' => [
            'key' => 'KnockedDownAllowed',
            'name' => 'KnockedDownAllowed',
            'type' => 'boolean',
            'group' => 'Advanced',
            'default' => false,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'WIP: Activating this setting may cause visual desynchronization of player positions.',
                'DE' => 'In Arbeit: Die Aktivierung dieser Einstellung kann zu einer visuellen Desynchronisation der Spielerpositionen führen.',
            ],
        ],
        'SneakModeHideFromOtherPlayers' => [
            'key' => 'SneakModeHideFromOtherPlayers',
            'name' => 'SneakModeHideFromOtherPlayers',
            'type' => 'boolean',
            'group' => 'Advanced',
            'default' => true,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => NULL,
                'DE' => NULL,
            ],
        ],
        'UltraSpeedDoesnotAffectToAnimals' => [
            'key' => 'UltraSpeedDoesnotAffectToAnimals',
            'name' => 'UltraSpeedDoesnotAffectToAnimals',
            'type' => 'boolean',
            'group' => 'Advanced',
            'default' => false,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => NULL,
                'DE' => NULL,
            ],
        ],
        'WorkshopItems' => [
            'key' => 'WorkshopItems',
            'name' => 'WorkshopItems',
            'type' => 'string',
            'group' => 'Advanced',
            'default' => NULL,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'List Workshop Mod IDs for the server to download. Each must be separated by a semicolon. Example: WorkshopItems=514427485;513111049',
                'DE' => 'Liste von Workshop Mod IDs für den Server zum Download. Getrennt durch ein Semikolon ( ; ). Beispiel: WorkshopItems=514427485;513111049',
            ],
        ],
        'SteamVAC' => [
            'key' => 'SteamVAC',
            'name' => 'SteamVAC',
            'type' => 'boolean',
            'group' => 'Advanced',
            'default' => true,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Enable the Steam VAC system',
                'DE' => 'Aktiviert das Steam-VAC-System',
            ],
        ],
        'LoginQueueEnabled' => [
            'key' => 'LoginQueueEnabled',
            'name' => 'LoginQueueEnabled',
            'type' => 'boolean',
            'group' => 'Advanced',
            'default' => false,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => NULL,
                'DE' => NULL,
            ],
        ],
        'LoginQueueConnectTimeout' => [
            'key' => 'LoginQueueConnectTimeout',
            'name' => 'LoginQueueConnectTimeout',
            'type' => 'integer',
            'group' => 'Advanced',
            'default' => 60,
            'min' => 20,
            'max' => 1200,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => NULL,
                'DE' => NULL,
            ],
        ],
        'server_browser_announced_ip' => [
            'key' => 'server_browser_announced_ip',
            'name' => 'server_browser_announced_ip',
            'type' => 'string',
            'group' => 'Advanced',
            'default' => NULL,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Set the IP from which the server is broadcast. This is for network configurations with multiple IP addresses, such as server farms',
                'DE' => 'Leg hier die IP fest unter dem der Server zu erreichen ist. Für Netzwerkkonfigurationen mit mehreren IP-Adressen wie Serverfarmen',
            ],
        ],
        'BloodSplatLifespanDays' => [
            'key' => 'BloodSplatLifespanDays',
            'name' => 'BloodSplatLifespanDays',
            'type' => 'integer',
            'group' => 'Advanced',
            'default' => 0,
            'min' => 0,
            'max' => 365,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Number of days before old blood splats are removed.<br>Removal happens when map chunks are loaded.<br>Zero means they will never disappear',
                'DE' => 'Anzahl der Tage, bevor alte Blutspritzer entfernt werden.<br>Entfernung erfolgt, wenn Kartenteile geladen werden.<br>Zero bedeutet nie entfernen.',
            ],
        ],
        'BanKickGlobalSound' => [
            'key' => 'BanKickGlobalSound',
            'name' => 'BanKickGlobalSound',
            'type' => 'boolean',
            'group' => 'Advanced',
            'default' => true,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => NULL,
                'DE' => NULL,
            ],
        ],
        'CarEngineAttractionModifier' => [
            'key' => 'CarEngineAttractionModifier',
            'name' => 'CarEngineAttractionModifier',
            'type' => 'double',
            'group' => 'Advanced',
            'default' => 0.5,
            'min' => 0.0,
            'max' => 10.0,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Modify the range of zombie attraction to cars. (Lower values can help with lag.)',
                'DE' => 'Ändert den Bereich, in dem Autos Zombies anziehen, niedrigere Werte können bei Server-Lags helfen.',
            ],
        ],
        'DisableVehicleTowing' => [
            'key' => 'DisableVehicleTowing',
            'name' => 'DisableVehicleTowing',
            'type' => 'boolean',
            'group' => 'Advanced',
            'default' => false,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Disables vehicle towing',
                'DE' => 'Deaktiviert das Abschleppen von Fahrzeugen',
            ],
        ],
        'DisableTrailerTowing' => [
            'key' => 'DisableTrailerTowing',
            'name' => 'DisableTrailerTowing',
            'type' => 'boolean',
            'group' => 'Advanced',
            'default' => false,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Disables trailer towing',
                'DE' => 'Deaktiviert das Abschleppen von Anhängern',
            ],
        ],
        'DisableBurntTowing' => [
            'key' => 'DisableBurntTowing',
            'name' => 'DisableBurntTowing',
            'type' => 'boolean',
            'group' => 'Advanced',
            'default' => false,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Disables burnt vehicle towing',
                'DE' => 'Deaktiviert das Abschleppen von ausgebrannten Fahrzeugen',
            ],
        ],
        'BadWordListFile' => [
            'key' => 'BadWordListFile',
            'name' => 'BadWordListFile',
            'type' => 'string',
            'group' => 'Advanced',
            'default' => NULL,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Path to the file with the list of words to be prohibited. Each word must be on a separate line',
                'DE' => 'Pfad zur Datei mit der Liste der zu verbietenden Wörter. Jedes Wort muss in einer separaten Zeile stehen',
            ],
        ],
        'GoodWordListFile' => [
            'key' => 'GoodWordListFile',
            'name' => 'GoodWordListFile',
            'type' => 'string',
            'group' => 'Advanced',
            'default' => NULL,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Path to the file with the list of words that should be allowed, even if they contain bad word. Each word should be on a separate line.',
                'DE' => 'Pfad zur Datei mit der Liste der erlaubten Wörter, auch wenn sie Schimpfwörter enthalten. Jedes Wort muss in einer separaten Zeile stehen.',
            ],
        ],
        'BadWordPolicy' => [
            'key' => 'BadWordPolicy',
            'name' => 'BadWordPolicy',
            'type' => 'enum',
            'group' => 'Advanced',
            'default' => 3,
            'min' => 1,
            'max' => 3,
            'numValues' => 3,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'What to do with the sender of a bad word in the chat: 1 - ban, 2 - kick, 3 - record the violation in the database, 4 - mute',
                'DE' => 'Was tun bei jemandem, der im Chat ein Schimpfwort benutzt? 1 - Bannen, 2 - Kicken, 3 - Verstoß in der Datenbank protokollieren, 4 - Stummschalten',
            ],
        ],
        'BadWordReplacement' => [
            'key' => 'BadWordReplacement',
            'name' => 'BadWordReplacement',
            'type' => 'string',
            'group' => 'Advanced',
            'default' => '[HIDDEN]',
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'The symbol or piece of text that will replace the bad word',
                'DE' => 'Das Symbol oder der Textabschnitt, der das Schimpfwort ersetzen soll',
            ],
        ],
        'AntiCheatSafety' => [
            'key' => 'AntiCheatSafety',
            'name' => 'AntiCheatSafety',
            'type' => 'enum',
            'group' => 'Advanced',
            'default' => 2,
            'min' => 1,
            'max' => 4,
            'numValues' => 4,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Disables safety system anti-cheat protection.',
                'DE' => 'Deaktiviert den Anti-Cheat-Schutz.',
            ],
        ],
        'AntiCheatSpeed' => [
            'key' => 'AntiCheatSpeed',
            'name' => 'AntiCheatSpeed',
            'type' => 'enum',
            'group' => 'Advanced',
            'default' => 2,
            'min' => 1,
            'max' => 4,
            'numValues' => 4,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Disables character speed anti-cheat protection.',
                'DE' => 'Deaktiviert den Anti-Cheat-Schutz für Charaktergeschwindigkeit.',
            ],
        ],
        'AntiCheatNoClip' => [
            'key' => 'AntiCheatNoClip',
            'name' => 'AntiCheatNoClip',
            'type' => 'enum',
            'group' => 'Advanced',
            'default' => 4,
            'min' => 1,
            'max' => 4,
            'numValues' => 4,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Disables character no-clipping anti-cheat protection.',
                'DE' => 'Deaktiviert denCharakter no-clip Anti-Cheat.',
            ],
        ],
        'AntiCheatHit' => [
            'key' => 'AntiCheatHit',
            'name' => 'AntiCheatHit',
            'type' => 'enum',
            'group' => 'Advanced',
            'default' => 2,
            'min' => 1,
            'max' => 4,
            'numValues' => 4,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Disables character hit anti-cheat protection.',
                'DE' => 'Deaktiviert den Anti-Cheat-Schutz für Charaktertreffer.',
            ],
        ],
        'AntiCheatPacketException' => [
            'key' => 'AntiCheatPacketException',
            'name' => 'AntiCheatPacketException',
            'type' => 'enum',
            'group' => 'Advanced',
            'default' => 4,
            'min' => 1,
            'max' => 4,
            'numValues' => 4,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Disables packet exception checks anti-cheat protection.',
                'DE' => 'Deaktiviert den Anti-Cheat für Packetprüfung.',
            ],
        ],
        'AntiCheatPermission' => [
            'key' => 'AntiCheatPermission',
            'name' => 'AntiCheatPermission',
            'type' => 'enum',
            'group' => 'Advanced',
            'default' => 2,
            'min' => 1,
            'max' => 4,
            'numValues' => 4,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Disables player permissions anti-cheat protection.',
                'DE' => 'Deaktiviert den Anti-Cheat-Schutz für Spielerbefugnisse.',
            ],
        ],
        'AntiCheatXP' => [
            'key' => 'AntiCheatXP',
            'name' => 'AntiCheatXP',
            'type' => 'enum',
            'group' => 'Advanced',
            'default' => 2,
            'min' => 1,
            'max' => 4,
            'numValues' => 4,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Disables player XP anti-cheat protection.',
                'DE' => 'Deaktiviert den Anti-Cheat-Schutz für Spieler-EP.',
            ],
        ],
        'AntiCheatSafeHouse' => [
            'key' => 'AntiCheatSafeHouse',
            'name' => 'AntiCheatSafeHouse',
            'type' => 'enum',
            'group' => 'Advanced',
            'default' => 2,
            'min' => 1,
            'max' => 4,
            'numValues' => 4,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Disables safehouse anti-cheat protection.',
                'DE' => 'Deaktiviert den Anti-Cheat-Schutz für Verstecke.',
            ],
        ],
        'AntiCheatPlayer' => [
            'key' => 'AntiCheatPlayer',
            'name' => 'AntiCheatPlayer',
            'type' => 'enum',
            'group' => 'Advanced',
            'default' => 2,
            'min' => 1,
            'max' => 4,
            'numValues' => 4,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Disables player anti-cheat protection.',
                'DE' => 'Deaktiviert den Spieler Anti-Cheat.',
            ],
        ],
        'AntiCheatChecksum' => [
            'key' => 'AntiCheatChecksum',
            'name' => 'AntiCheatChecksum',
            'type' => 'enum',
            'group' => 'Advanced',
            'default' => 2,
            'min' => 1,
            'max' => 4,
            'numValues' => 4,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Disables checksum anti-cheat protection.',
                'DE' => 'Deaktiviert den Anti-Cheat-Schutz für Checksummen.',
            ],
        ],
        'MultiplayerStatisticsPeriod' => [
            'key' => 'MultiplayerStatisticsPeriod',
            'name' => 'MultiplayerStatisticsPeriod',
            'type' => 'integer',
            'group' => 'Advanced',
            'default' => 1,
            'min' => 0,
            'max' => 10,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Sets the multiplayer update period in seconds. Statistics is disabled if value is 0.',
                'DE' => 'Setzt die Aktualisierungsrate für Multiplayer in Sekunden. Statistiken deaktiviert wenn der Wert 0 ist.',
            ],
        ],
        'DisableScoreboard' => [
            'key' => 'DisableScoreboard',
            'name' => 'DisableScoreboard',
            'type' => 'boolean',
            'group' => 'Advanced',
            'default' => false,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Disables scoreboard.',
                'DE' => 'Deakiviert das Scoreboard.',
            ],
        ],
        'HideAdminsInPlayerList' => [
            'key' => 'HideAdminsInPlayerList',
            'name' => 'HideAdminsInPlayerList',
            'type' => 'boolean',
            'group' => 'Advanced',
            'default' => false,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Hides admins in the player list.',
                'DE' => 'Admins werden in der Spielerliste nicht angezeigt.',
            ],
        ],
        'MaxPacketsPerSecond' => [
            'key' => 'MaxPacketsPerSecond',
            'name' => 'MaxPacketsPerSecond',
            'type' => 'integer',
            'group' => 'Advanced',
            'default' => 300,
            'min' => 100,
            'max' => 1000,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Sets the limit for processing network packets from each client on the server.',
                'DE' => 'Legt das Limit für die Verarbeitung von Netzwerkpaketen von jedem Client auf dem Server fest.',
            ],
        ],
        'ShowCoordinates' => [
            'key' => 'ShowCoordinates',
            'name' => 'ShowCoordinates',
            'type' => 'boolean',
            'group' => 'Advanced',
            'default' => false,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'Shows player character coordinates in the lower right corner.',
                'DE' => 'Zeigt die Koordinaten der Spielfigur in der unteren rechten Ecke an.',
            ],
        ],
        'Seed' => [
            'key' => 'Seed',
            'name' => 'Seed',
            'type' => 'string',
            'group' => 'Advanced',
            'default' => NULL,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => 'The worldgen seed used to generate the world.<br>If you want to change this, put a new value in and delete map_worldgen.bin in your save directory.',
                'DE' => 'Der für die Weltgenerierung verwendete Seed.<br>Wenn du diesen ändern möchtest, gib einen neuen Wert ein und lösche die Datei map_worldgen.bin in deinem Speicherordner.',
            ],
        ],
        'UsePhysicsHitReaction' => [
            'key' => 'UsePhysicsHitReaction',
            'name' => 'UsePhysicsHitReaction',
            'type' => 'boolean',
            'group' => 'Advanced',
            'default' => false,
            'min' => NULL,
            'max' => NULL,
            'numValues' => NULL,
            'defaultIsGenerated' => false,
            'tooltips' => [
                'EN' => NULL,
                'DE' => NULL,
            ],
        ],
    ];
}
